"use strict";
const $=id=>document.getElementById(id), heroes={gear:{name:"Ника",gift:true,influence:1,stress:0},plain:{name:"Лев",gift:false,influence:1,stress:1}};
let current="gear",result=null,request=false,records=[];
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const n=id=>Math.max(0,Math.min(id==="target"?99:30,Number($(id).value)||0));
function pool(){return Math.max(1,n("attribute")+n("skill")+n("ability")+n("bond")+n("adv")-n("hind"))}
function render(){const h=heroes[current];$("resources").textContent=`${h.name} · Ступень 2 · Влияние ${h.influence} · Стресс ${h.stress}/3`;$("pool").innerHTML=`<strong>${pool()}D6</strong><small>Атрибут ${n("attribute")} + Навык ${n("skill")} + ${h.gift?"гаджет":"Способность"} ${n("ability")} + Связь ${n("bond")} + Преимущество ${n("adv")} − Помеха ${n("hind")}</small>`;$("result").hidden=!result;$("request-status").textContent=request?`Демонстрационный запрос Нарратора для ${h.name} · цель ${n("target")} · Риск согласован. Не отправлен по сети.`:"Свободный бросок · запрос не требуется.";$("target").disabled=request;$("action").disabled=request;$("risk").disabled=request;$("request").textContent=request?"Отменить демонстрационный запрос":"Показать пример запроса Нарратора";
if(result){const blocked=result.closed?"Действие завершено.":result.allIn?"Ва-банк уже применён к этому броску. Завершите действие.":result.riskApplied?"Риск уже применён; окно Ва-банк закрыто.":h.influence<1?"Ва-банк недоступен: нужно 1 Влияние, сейчас 0. У героя нет Дара для другой оплаты.":"Цена Ва-банк: 1 Влияние. Пул и условия исходного действия сохраняются.";$("result").innerHTML=`<h2>3. ${result.closed?"Действие завершено":result.allIn?"Итог Ва-банк":"Провал"}</h2><p><strong>${escapeHtml(h.name)} · ${result.pool}D6 · ${result.allIn?3:0} Успехов · цель ${result.target}</strong></p><p>${escapeHtml(result.action)}</p><p>Риск: ${escapeHtml(result.risk)}</p><p>${result.riskApplied?"Оговорённый Риск применён. Завершите действие или продолжите сцену с Нарратором.":result.allIn?"Демонстрация нового результата. Правила и последствия Ва-банк требуют отдельного подтверждения по LionWing; движок здесь не реализован.":"Награда не получена. Выберите Ва-банк или согласуйте применение Риска с Нарратором."}</p><div class="actions"><button id="all-in" ${result.closed||result.riskApplied||result.allIn||h.influence<1?"disabled":""}>Ва-банк · −1 Влияние</button><button id="apply-risk" ${result.closed||result.riskApplied||result.allIn||h.stress>=3?"disabled":""}>Применить оговорённый Риск · +1 Стресс</button><button id="finish" ${result.closed?"disabled":""}>Завершить действие</button></div><p>${escapeHtml(blocked)}</p><small>${h.stress>=3?"Стресс максимален. Здесь нельзя применить ещё 1 Стресс; исход персонажа требует решения Нарратора.":"Риск применяется отдельно и один раз. Числа меняются только у демонстрационного героя."}</small>`;}
$("roll").disabled=Boolean(result&&!result.closed);$("history-title").textContent=`Записи этого примера · ${records.length}`;$("history").innerHTML=records.map(s=>`<li>${escapeHtml(s)}</li>`).join("")||"<li>Записей пока нет.</li>";}
function chooseHero(){current=$("hero").value;result=null;request=false;$("ability").innerHTML=heroes[current].gift?'<option value="0">Без Способности или гаджета</option><option value="2">Гаджет: Универсальная отмычка · Ранг 2</option>':'<option value="0">Без Способности</option><option value="1">Способность: Чувствовать металл · Ранг 1</option>';$("gift-note").textContent=heroes[current].gift?"Технарь: можно выбрать свой гаджет вместо Способности. Одновременно — один источник.":"У Льва нет Технаря: управление собственными гаджетами скрыто. Передача чужого гаджета в этом примере не реализована.";render()}
$("hero").addEventListener("change",chooseHero);
for(const id of ["attribute","skill","ability","bond","adv","hind","target"])$(id).addEventListener("input",render);
$("empty").onclick=()=>{heroes[current].influence=0;render()};$("reset").onclick=()=>{heroes.gear.influence=heroes.plain.influence=1;heroes.gear.stress=0;heroes.plain.stress=1;result=null;request=false;render()};
$("request").onclick=()=>{request=!request;render()};
$("roll").onclick=()=>{if(result&&!result.closed)return;const target=Math.max(1,n("target"));$("target").value=target;result={pool:pool(),target,action:$("action").value,risk:$("risk").value,closed:false,riskApplied:false,allIn:false};records.unshift(`${heroes[current].name}: провал · ${result.pool}D6 · цель ${target}`);records=records.slice(0,10);render()};
$("result").addEventListener("click",event=>{const h=heroes[current],id=event.target.id;if(!result)return;if(id==="all-in"&&!result.closed&&!result.riskApplied&&!result.allIn&&h.influence>0){h.influence--;result.allIn=true;records.unshift(`${h.name}: демонстрация Ва-банк · −1 Влияние`)}if(id==="apply-risk"&&!result.closed&&!result.riskApplied&&!result.allIn&&h.stress<3){h.stress++;h.influence++;result.riskApplied=true;records.unshift(`${h.name}: оговорённый Риск · +1 Стресс, +1 Влияние (демонстрационная модель)`)}if(id==="finish"&&!result.closed){result.closed=true;request=false;records.unshift(`${h.name}: действие завершено`)}records=records.slice(0,10);render()});
$("clear-history").onclick=()=>{records=[];render()};document.querySelectorAll("[data-page]").forEach(button=>button.onclick=()=>{const page=button.dataset.page;$("workspace").hidden=page!=="Инструменты";$("other").hidden=page==="Инструменты";$("other-title").textContent=page;document.querySelectorAll("nav button").forEach(b=>b.dataset.page===page?b.setAttribute("aria-current","page"):b.removeAttribute("aria-current"))});chooseHero();



