const $=s=>document.querySelector(s),main=$('#main');
const state={mode:'table',hero:'Нари',role:'Игрок',edit:false,section:'Основа',query:'',kind:'Все',draft:'Атака',returnMode:null,rule:null,heroName:{Нари:'Нари',Орден:'Орден'},focus:null};
const rules=[{name:'Реакция',kind:'Действия',text:'Окно ответа на действие другого участника. Демо показывает место подсказки и возврата к незавершённому действию.'},{name:'Стресс',kind:'Ресурсы',text:'Ресурс героя. Текущее значение и максимум должны быть различимы. Здесь приведён только демонстрационный текст.'},{name:'Атака',kind:'Действия',text:'Выберите действие, цель и проверьте стоимость до подтверждения. Демонстрация интерфейса, не автоматизация механики.'},{name:'Движение',kind:'Действия',text:'Путь и доступная дистанция читаются на поле. Это демонстрационный пересказ.'},{name:'Связь',kind:'Герой',text:'Краткая справка о выбранной Связи. Детали открываются по запросу.'}];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const title=(name,help,extra='')=>`<div class="heading"><div><h1>${name}</h1><p>${help}</p></div>${extra}</div>`;
function render(){document.querySelectorAll('[data-mode]').forEach(b=>{b.removeAttribute('aria-current');if(b.dataset.mode===state.mode)b.setAttribute('aria-current','page')});
if(state.mode==='hero')main.innerHTML=title(esc(state.heroName[state.hero]),state.edit?'Редактор · изменения остаются в этом демо':'Игровой лист · связан с текущим контекстом',`<button id="edit">${state.edit?'Играть':'Редактировать'}</button>`)+(state.edit?`<div class="split"><aside>${['Основа','Атрибуты','Техники','Гаджеты'].map(x=>`<button data-section="${x}" aria-pressed="${state.section===x}">${x}</button>`).join('')}</aside><section><h2>${state.section}</h2>${state.section==='Основа'?`<label class="field">Имя героя<input id="name" value="${esc(state.heroName[state.hero])}"></label><label class="field">Концепция<input placeholder="Что движет героем?"></label>`:state.section==='Атрибуты'?`<div class="field-grid">${['Сила','Ловкость','Разум','Дух'].map(x=>`<label class="field">${x}<select><option>2</option><option>3</option><option>4</option></select></label>`).join('')}</div>`:`<p>Выбранное: ${state.section==='Техники'?'Следопыт · Ранг 1':'Призрачный плащ · Ранг 2'}</p><details><summary>Открыть описание и параметры</summary><label class="field">Название<input value="${state.section==='Техники'?'Следопыт':'Призрачный плащ'}"></label><p>Демонстрация компактного редактора.</p></details>`}<div class="banner">Бюджет: 6 / 6 · редактирование не переключает режим.</div></section></div>`:`<div class="stats"><div>Здоровье<strong>10 / 19</strong></div><div>Фокус<strong>2 / 3</strong></div><div>Стресс<strong>1 / 3</strong></div></div><div class="split"><aside><button data-mode="tools">Подготовить бросок</button><button data-mode="table" class="primary">К действиям на Столе</button><button id="files">Файлы и печать</button></aside><section><h2>Использовать сейчас</h2>${['Ловкость · 3D6','Скрытность · +2D6','Призрачный плащ · +2D6'].map(x=>`<div class="row"><strong>${x}</strong><button data-tool="${x}">В бросок</button></div>`).join('')}<details><summary>Техники · 3 выбранные</summary><p>Краткое описание выбранных техник.</p><button data-rule="Атака">Правило действия</button></details><details><summary>Связи и мировоззрение</summary><p>Вторичные детали листа.</p></details></section></div>`);
if(state.mode==='table')main.innerHTML=title('Стол','Затопленный храм · текущая Сцена',`<button data-mode="hero">Лист героя</button>`)+`<div class="split"><aside><h2>${esc(state.heroName[state.hero])}</h2><p>${esc(state.role)} · Здоровье 10 / 19</p><div class="banner">Черновик: ${esc(state.draft)}</div><label class="field">Действие<select id="action">${['Атака','Движение','Реакция'].map(x=>`<option ${state.draft===x?'selected':''}>${x}</option>`).join('')}</select></label><button data-rule="${state.draft}">Проверить правило</button><button id="resolve" class="primary">Подтвердить демо</button><details><summary>Журнал и участники</summary><p>Орден ждёт ответа · Нарратор ведёт Сцену.</p></details></aside><section><div class="board" aria-label="Демонстрационное поле"><span class="token" style="left:20%;top:35%">${esc(state.heroName[state.hero])}</span><span class="token" style="left:65%;top:55%">Страж</span></div><p>Черновик действия остаётся при переходе к справке.</p>${state.role==='Нарратор'?'<details><summary>Управление Сценой</summary><p>Подготовка, резервная копия и участники находятся здесь.</p></details>':''}</section></div>`;
if(state.mode==='tools')main.innerHTML=title('Инструменты','Источник и герой остаются видны')+`<div class="split"><aside><h2>${esc(state.heroName[state.hero])}</h2><button data-mode="hero">Выбрать источник в листе</button><button data-mode="table">Вернуться к Столу</button></aside><section><h2>Бросок</h2><div class="banner">${esc(state.source||'Ловкость · 3D6')}</div><label class="field">Задача<input id="task" value="${esc(state.task||'Пробраться мимо стража')}"></label><button id="roll" class="primary">Бросить демо-пул</button><button data-rule="Реакция">Справка рядом</button><output id="roll-result"></output><details><summary>Связи, часы и история</summary><p>Вторичные инструменты раскрываются по запросу.</p></details></section></div>`;
if(['rules','reference'].includes(state.mode))main.innerHTML=title(state.mode==='rules'?'Правила':'Справочник',state.mode==='rules'?'Читайте главу или найдите нужное правило':'Термины и действия в одном списке',state.returnMode?'<button id="return">← К исходному действию</button>':'')+`<div class="split"><aside>${['Все','Действия','Ресурсы','Герой'].map(x=>`<button data-kind="${x}" aria-pressed="${state.kind===x}">${x}</button>`).join('')}<details><summary>Источник</summary><p>LionWing · в демо используется условный текст.</p></details></aside><section><label for="query">Поиск по названию и описанию</label><input type="search" id="query" placeholder="Например, Реакция" value="${esc(state.query)}"><p id="count"></p><div class="results" id="results"></div></section></div>`;
if(state.mode==='print')main.innerHTML=title('Предпросмотр печати','Компактный лист · демонстрация',`<button data-mode="hero">Вернуться к листу</button>`)+`<article class="print-sheet"><h2>${esc(state.heroName[state.hero])}</h2><p>LionWing · Здоровье 10 / 19 · Фокус 2 / 3</p><hr><p>Ловкость 3 · Скрытность +2 · Призрачный плащ +2</p><p>Техники: Следопыт · Связь: Орден</p><button id="native-print">Печать браузера</button></article>`;
if($('#results'))results();}
function results(){const found=rules.filter(r=>(state.kind==='Все'||r.kind===state.kind)&&(r.name+' '+r.text).toLowerCase().includes(state.query.toLowerCase()));$('#count').textContent=`Найдено: ${found.length}`;$('#results').innerHTML=found.map(r=>`<button data-rule="${r.name}"><small>${r.kind}</small><strong>${r.name}</strong><span>${r.text}</span></button>`).join('')||'<p>Нет результатов. Измените запрос или выберите «Все».</p>';}
function switchMode(mode){state.mode=mode;render();main.focus();}
function showRule(name){state.focus=document.activeElement;state.rule=rules.find(r=>r.name===name)||rules[0];$('#rule-title').textContent=state.rule.name;$('#rule-body').textContent=state.rule.text;$('#rule').showModal();}
function closeRule(){$('#rule').close();state.focus?.focus();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.mode)switchMode(b.dataset.mode);if(b.dataset.section){state.section=b.dataset.section;render();}if(b.dataset.kind){state.kind=b.dataset.kind;render();}if(b.dataset.rule)showRule(b.dataset.rule);if(b.dataset.tool){state.source=b.dataset.tool;switchMode('tools');}if(b.id==='edit'){state.edit=!state.edit;render();}if(['settings','files'].includes(b.id))$('#preferences').showModal();if(['close-rule','rule-return'].includes(b.id))closeRule();if(b.id==='full-rule'){state.returnMode=state.mode;state.query=state.rule.name;closeRule();switchMode('rules');}if(b.id==='return'){const m=state.returnMode;state.returnMode=null;switchMode(m);}if(b.id==='print'){$('#preferences').close();switchMode('print');}if(b.id==='native-print')window.print();if(b.id==='roll')$('#roll-result').textContent=' Демо: 6, 4, 2 · без расхода ресурсов';if(b.id==='resolve'){$('#notice').textContent='Демо подтверждено · состояние игры не меняется';}});
document.addEventListener('input',e=>{if(e.target.id==='query'){state.query=e.target.value;results();}if(e.target.id==='name')state.heroName[state.hero]=e.target.value;if(e.target.id==='task')state.task=e.target.value;});
$('#hero').onchange=e=>{state.hero=e.target.value;render();};$('#role').onchange=e=>{state.role=e.target.value;render();};document.addEventListener('change',e=>{if(e.target.id==='action'){state.draft=e.target.value;render();}});$('#theme').onchange=e=>document.body.classList.toggle('night',e.target.value==='night');$('#import').onchange=async e=>{try{const data=JSON.parse(await e.target.files[0].text());const name=data.name||data.hero?.name;if(!name)throw Error();state.heroName[state.hero]=String(name);$('#importstatus').textContent='Демо-имя принято. Файл не сохранён.';render();}catch{$('#importstatus').textContent='Нужен JSON с полем name.'}};render();
