"use strict";
const lessons=window.DAWN_LESSONS||[];
const params=new URLSearchParams(location.search);const lesson=lessons.find(x=>x.id===params.get("lesson"))||lessons[0];
const $=id=>document.getElementById(id),esc=v=>String(v??"").replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]));
const BEAT_MS=6800;let elapsed=0,last=0,playing=false,frame=0,current=-1,visualTimers=[];
document.title=`DAWN · ${lesson.id} · ${lesson.title}`;$("lesson-number").textContent=`УРОК ${lesson.id} / 12`;$("lesson-title").textContent=lesson.title;$("lesson-subtitle").textContent=lesson.subtitle;
const lessonIndex=lessons.indexOf(lesson),lessonHref=x=>`player.html?lesson=${x.id}`;
const prevLesson=lessons[lessonIndex-1],nextLesson=lessons[lessonIndex+1];
if(prevLesson){$("prev-lesson").href=lessonHref(prevLesson);$("prev-lesson").title=`${prevLesson.id}. ${prevLesson.title}`}else $("prev-lesson").classList.add("disabled");
if(nextLesson){$("next-lesson").href=lessonHref(nextLesson);$("next-lesson").title=`${nextLesson.id}. ${nextLesson.title}`}else{$("next-lesson").href="00_оглавление.html";$("next-lesson").title="Вернуться к оглавлению";$("next-lesson").querySelector("span").textContent="готово"}
function terms(values,cls="v-equation"){return `<div class="${cls}">${values.map(x=>`<span class="term">${esc(x)}</span>`).join("")}</div>`}
function dice(values,cls="v-dice",extra=""){return `<div class="${cls} ${extra}">${values.map((v,i)=>`<span class="die ${v===6?"crit":v>=4?"success":""}" data-final="${v}" aria-label="Кость: ${v}" style="--i:${i}">${v}</span>`).join("")}</div>`}
function renderVisual(type,values){
 const simple={equation:"v-equation",flow:"v-flow",burst:"v-burst",threshold:"v-threshold",versus:"v-versus",balance:"v-balance",split:"v-split",interrupt:"v-interrupt"};
 if(simple[type])return terms(values,simple[type]);
 if(type==="dice"||type==="pool")return dice(values,type==="pool"?"v-pool":"v-dice");
 if(type==="dice-roll")return `<div class="dice-arena"><span class="throw-arc" aria-hidden="true"></span>${dice(values,"v-dice v-dice-roll")}<span class="impact" aria-hidden="true"></span><b class="roll-callout">БРОСОК</b></div>`;
 if(type==="dice-resolve")return `${dice(values,"v-dice v-dice-resolve")}<div class="success-count"><strong>${values.filter(v=>v>=4).length}</strong><span>УСПЕХА</span></div>`;
 if(type==="crit-chain")return `<div class="v-crit-chain">${values.map((v,i)=>`${i?'<span class="chain-arrow">→</span>':''}<span class="chain-die die ${v===6?'crit':'success'}" data-final="${v}" style="--i:${i}">${v}</span>`).join("")}<small>6 добавляет новую кость</small></div>`;
 if(type==="advantage-add"){const [base,bonus]=values;return `<div class="v-advantage"><div class="pool-row base">${Array.from({length:base},(_,i)=>`<span class="die" style="--i:${i}">◆</span>`).join("")}</div><span class="math-sign">+</span><div class="bonus-row">${Array.from({length:bonus},(_,i)=>`<span class="die advantage" style="--i:${i}">+</span>`).join("")}</div><strong>${base+bonus}D6</strong></div>`}
 if(type==="pool-math"){const [base,adv,hind]=values,result=base+adv-hind;return `<div class="v-pool-math"><div class="pool-row source-pool">${Array.from({length:base},(_,i)=>`<span class="die base-die" style="--i:${i}">◆</span>`).join("")}</div><div class="modifier-row">${Array.from({length:adv},(_,i)=>`<span class="die advantage ${i>=adv-hind?'cancelled':'survivor'}" style="--i:${i}">+</span>`).join("")}${Array.from({length:hind},(_,i)=>`<span class="die hindrance cancelled" style="--i:${i}">−</span>`).join("")}</div><div class="cancel-flash" aria-hidden="true">×</div><div class="pool-row result-pool">${Array.from({length:result},(_,i)=>`<span class="die ${i>=base?'advantage':''}" style="--i:${i}">${i>=base?'+':'◆'}</span>`).join("")}</div><strong>${base} + ${adv} − ${hind} = ${result}D6</strong></div>`}
 if(type==="outcome-track"){const [successes,target,extreme]=values;return `<div class="v-outcome-track"><div class="outcome-labels"><span>Провал</span><span>Минимальный</span><span>Крайний</span></div><div class="outcome-line"><i style="--x:${target/Math.max(extreme,successes)*100}%"></i><i style="--x:${extreme/Math.max(extreme,successes)*100}%"></i><b style="--x:${successes/Math.max(extreme,successes)*100}%">${successes}</b></div><strong>${successes>=extreme?'КРАЙНИЙ УСПЕХ':successes>=target?'МИНИМАЛЬНЫЙ УСПЕХ':'ПРОВАЛ'}</strong></div>`}
 if(type==="pool-build"){const [attribute,skill,ability,hindrance,result]=values;return `<div class="v-pool-build"><div class="build-sources"><span>${attribute}D6<small>Атрибут</small></span><span>+${skill}<small>Навык</small></span><span>+${ability}<small>Способность</small></span><span class="negative">${hindrance}<small>Помеха</small></span></div><div class="merge-lines" aria-hidden="true"></div>${dice(Array.from({length:result},(_,i)=>[6,4,2,5,3][i]),"v-pool final-pool")}</div>`}
 if(type==="round-loop")return `<div class="v-round-loop"><div class="round-core">РАУНД <b>2</b></div><span class="ap">3 ОД</span><span class="spend">−1&nbsp; −1&nbsp; −1</span><span class="tension">НАПРЯЖЕНИЕ +1</span><i aria-hidden="true"></i></div>`;
 if(type==="health-cycle"){const [max,guts]=values;return `<div class="v-health-cycle"><div class="cycle-meter"><i></i></div><span class="wound">РАНА +1</span><div class="refill" style="--refill:${guts/max*100}%"><i></i></div><strong>СТОЙКОСТЬ · ${guts}</strong></div>`}
 if(type==="focus-spend"){const [total,spend]=values;return `<div class="v-focus-spend"><div class="focus-pips">${Array.from({length:total},(_,i)=>`<span class="pip ${i>=total-spend?'spent':''}" style="--i:${i}">✦</span>`).join("")}</div><span class="focus-arrow">→</span><div class="focus-strike">АТАКА <b>+${spend}</b></div></div>`}
 if(type==="tech-growth")return `<div class="v-tech-growth">${values.map((v,i)=>`<div class="tech-level" style="--i:${i}"><span>УРОВЕНЬ ${v}</span><strong>${['ОСНОВА','УСИЛЕНИЕ','КУЛЬМИНАЦИЯ'][i]}</strong><i></i></div>`).join("")}</div>`;
 if(type==="attributes")return `<div class="v-attributes">${values.map((v,i)=>`<div class="mini-card" style="--i:${i}"><span>${esc(v)}</span><strong>${[4,3,2,2][i]}</strong></div>`).join("")}</div>`;
 if(type==="stat")return `<div class="v-stat"><b>${esc(values[0])}</b><strong>${esc(values[1])}</strong><small>${esc(values[2])}</small></div>`;
 if(type==="ladder")return `<div class="v-ladder">${values.map((v,i)=>`<span class="step" style="--i:${i}">${v}</span>`).join("")}</div>`;
 if(type==="pips")return `<div class="v-pips">${values.map((v,i)=>`<span class="pip" style="--i:${i}">${esc(v)}</span>`).join("")}</div>`;
 if(["tags","outcomes","sources","rewards","targets"].includes(type))return `<div class="v-${type}">${values.map(v=>`<span class="pill">${esc(v)}</span>`).join("")}</div>`;
 if(type==="source")return terms(values,"v-flow");
 if(type==="card")return `<div class="v-card"><b>${esc(values[0])}</b><p>${esc(values[1])}</p></div>`;
 if(type==="meter"){const [value,max,label]=values;return `<div class="v-meter"><div class="meter-label"><span>${esc(label)}</span><strong>${value} / ${max}</strong></div><div class="meter"><i style="--fill:${Math.max(0,Math.min(100,value/max*100))}%"></i></div></div>`}
 if(type==="orbit")return `<div class="v-orbit"><div class="orbit-core">${esc(values[1])}</div>${values.filter((_,i)=>i!==1).map((v,i)=>`<span class="orb" style="--angle:${i*120}deg">${esc(v)}</span>`).join("")}</div>`;
 if(type==="tree")return `<div class="v-tree"><span class="tree-root">${esc(values[0])}</span><span class="branch" style="--rot:-32deg">${esc(values[1])}</span><span class="branch" style="--rot:32deg">${esc(values[2])}</span></div>`;
 if(type==="timeline")return `<div class="v-timeline">${values.map((v,i)=>`<div class="mini-card" style="--i:${i}"><span>${i+1}</span><strong>${esc(v)}</strong></div>`).join("")}</div>`;
 return terms(values);
}
function clearVisualTimers(){visualTimers.forEach(clearInterval);visualTimers=[]}
function animateDice(){document.querySelectorAll(".v-dice-roll .die,.v-crit-chain .die").forEach((die,i)=>{let turns=0;const final=die.dataset.final;const timer=setInterval(()=>{die.textContent=String(1+Math.floor(Math.random()*6));if(++turns>8+i*2){clearInterval(timer);die.textContent=final}},70);visualTimers.push(timer)})}
function showBeat(index){index=Math.max(0,Math.min(lesson.beats.length-1,index));if(index===current)return;clearVisualTimers();current=index;const [title,body,type,values]=lesson.beats[index];$("beat-kicker").textContent=`ШАГ ${index+1} ИЗ ${lesson.beats.length}`;$("beat-title").textContent=title;$("beat-body").textContent=body;const old=$("visual");old.innerHTML=renderVisual(type,values);old.classList.remove("visual");void old.offsetWidth;old.classList.add("visual");const copy=old.previousElementSibling;copy.style.animation="none";void copy.offsetWidth;copy.style.animation="";if(type==="dice-roll"||type==="crit-chain")animateDice()}
function format(ms){const s=Math.floor(ms/1000);return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
function paint(){const total=lesson.beats.length*BEAT_MS;elapsed=Math.max(0,Math.min(total,elapsed));showBeat(Math.min(lesson.beats.length-1,Math.floor(elapsed/BEAT_MS)));$("progress").style.width=`${elapsed/total*100}%`;$("time").textContent=`${format(elapsed)} / ${format(total)}`;$("play").textContent=playing?"❚❚":"▶";}
function tick(now){if(!playing)return;elapsed+=now-last;last=now;if(elapsed>=lesson.beats.length*BEAT_MS){elapsed=lesson.beats.length*BEAT_MS;playing=false;}paint();if(playing)frame=requestAnimationFrame(tick)}
function toggle(){playing=!playing;cancelAnimationFrame(frame);if(playing){$("start").classList.add("hidden");last=performance.now();frame=requestAnimationFrame(tick)}paint()}
function seekBeat(delta){elapsed=Math.max(0,Math.min((lesson.beats.length-1)*BEAT_MS,Math.floor(elapsed/BEAT_MS)*BEAT_MS+delta*BEAT_MS));current=-1;paint()}
function restart(){elapsed=0;current=-1;playing=false;cancelAnimationFrame(frame);$("start").classList.remove("hidden");paint()}
$("start").onclick=toggle;$("play").onclick=toggle;$("prev").onclick=()=>seekBeat(-1);$("next").onclick=()=>seekBeat(1);$("restart").onclick=restart;
document.addEventListener("keydown",event=>{if(["Space","ArrowLeft","ArrowRight","KeyR"].includes(event.code))event.preventDefault();if(event.code==="Space")toggle();if(event.code==="ArrowLeft"&&!event.shiftKey)seekBeat(-1);if(event.code==="ArrowRight"&&!event.shiftKey)seekBeat(1);if(event.code==="ArrowLeft"&&event.shiftKey&&prevLesson)location.href=lessonHref(prevLesson);if(event.code==="ArrowRight"&&event.shiftKey)location.href=nextLesson?lessonHref(nextLesson):"00_оглавление.html";if(event.code==="KeyR")restart();});
paint();
