import assert from "node:assert/strict";
import fs from "node:fs";
import { loadHeroModel } from "./load-hero-model.mjs";

const model = loadHeroModel();
const ability = (name, rank = 1) => ({ enabled: true, name, rank, words: { verbs: ["ability.en.verbs.perceive"], nouns: ["ability.en.nouns.magic"], conditions: [] } });
const base = model.run('JSON.parse(JSON.stringify(blankHero("lionwing")))');
base.tier = 2;
base.attrBonus = { body: 1, talent: 1, spirit: 0, mind: 0 };
base.primaryOutlook = "quiet"; base.outlooks = ["quiet"];
base.gifts = ["quiet.gearhead", "quiet.knacks-and-hobbies", "quiet.technobabble"];
base.skills = [{ id: "skill", name: "Tinker", rank: 3 }, { id: "skill2", name: "Science", rank: 3 }];
base.ability = ability("Main", 2);
base.gadgets = [{ id: "sensor", status: "active", ability: ability("Sensor", 2) }, { id: "spare", status: "destroyed", ability: ability("Spare", 3) }];
base.techniques = { "altruist.alchemist": 3, "ruiner.spellcrafter": 3, "ruiner.cryomancer": 1 };
model.select(base);
let state = model.snapshot();
assert.equal(state.budgets.gadgetSpent, 2, "Only active gadgets consume Ranks");
assert.equal(state.budgets.paidGadgets, 0, "Gearhead's three Ranks pay first");
assert.equal(state.budgets.coreRankSpent, 8, "Gadgets never count as Skills");
assert.equal(state.budgets.skillSpent, 6);
assert.equal(model.run('abilityByKey("gadget:sensor").name'), "Sensor");
model.run('abilityByKey("gadget:sensor").rank=3');
assert.equal(model.run('S.ability.rank'), 2, "Gadget editing leaves the main Ability intact");
model.run('S.mods.gadgetSpent=2');
state = model.snapshot();
assert.equal(state.budgets.gadgetSpent, 5, "Legacy unrecorded spending remains additive");
assert.equal(state.budgets.paidGadgets, 2);
assert.equal(state.budgets.coreRankSpent, 10);
model.run('S.gadgets[0].status="destroyed"');
assert.equal(model.snapshot().budgets.coreRankSpent, 8, "Dismantling refunds paid gadget Ranks");
const portable = JSON.parse(model.run('JSON.stringify({format:"dawn-ru-hero",schema:2,hero:S})'));
model.select(portable.hero);
assert.equal(model.snapshot().hero.gadgets[0].status, "destroyed", "Portable JSON retains destroyed records and formulas");
assert.equal(model.snapshot().hero.gadgets[0].ability.words.nouns[0], "ability.en.nouns.magic");
model.run('S.gadgets[0].status="active";S.gifts=[];');
assert.equal(model.snapshot().hero.gadgets.length, 2, "Removing Gearhead preserves the saved gadget records");
assert.equal(model.snapshot().budgets.gadgetSpent, 0, "Dormant gadgets do not consume the shared budget");
assert.equal(model.run("heroGadgetsSheetMarkup()"), "", "Gadgets disappear from the sheet without Gearhead");
assert.equal(model.run("heroGadgetDiceSources().length"), 0);
model.run('S.gifts=["quiet.gearhead"];S.gadgets[0].ability.words.verbs=[];');
assert.ok(model.snapshot().issues.some(([kind, text]) => kind === "bad" && /Глагол/.test(text)), "An unfinished gadget cannot make the build appear complete");
model.select({ ...base, gadgets: [null, [], { id: "x\" onclick=bad", ability: ability("<img src=x>") }, { id: "duplicate", ability: ability("A") }, { id: "duplicate", ability: ability("B") }] });
state = model.snapshot();
assert.equal(state.hero.gadgets.length, 3);
assert.equal(new Set(state.hero.gadgets.map(item => item.id)).size, 3);
assert.ok(state.hero.gadgets.every(item => /^[a-zA-Z0-9_-]{1,80}$/.test(item.id)));
assert.ok(model.run("heroGadgetsSheetMarkup()").includes("&lt;img src=x&gt;"), "Gadget text must be escaped");
model.select({ ...base, rulesEdition: "ru-v0.9", gadgets: undefined, mods: { gadgetSpent: 3 } });
state = model.snapshot();
assert.deepEqual(state.hero.gadgets, [], "Old sheets without gadgets retain the old manual amount");
assert.equal(state.budgets.gadgetSpent, 3);
assert.equal(state.derived.hp, 14, "The old edition still uses its own Health formula");
const index = fs.readFileSync(new URL("../index.html", import.meta.url), "utf8");
const sw = fs.readFileSync(new URL("../sw.js", import.meta.url), "utf8");
assert.ok(index.indexOf("hero-gadgets.js") < index.indexOf("app-core.js"));
assert.ok(sw.includes('"./hero-gadgets.js"') && sw.includes('versioned("./hero-gadgets.css")'));
console.log("Hero gadgets QA passed: accounting, editing isolation, refunds, portable JSON, validation and legacy compatibility");
