import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const read=name=>fs.readFileSync(new URL(`../${name}`,import.meta.url),'utf8');
// DOM fixture preserves node identity and normal bubbling ownership. No browser/network.
function fixture(width=390){
 const frames=[],listeners=new Map(),observers=[],timers=new Map();let now=0,nextTimer=1,context={};
 class Element{
  constructor(tag='div',id='',classes=''){this.tagName=tag.toUpperCase();this.id=id;this.className=classes;this.children=[];this.parentElement=null;this.hidden=false;this.dataset={};this.attributes=new Map();this.height=100;this.style={values:new Map(),setProperty(name,value){this.values.set(name,value)},removeProperty(name){this.values.delete(name)}};this.classList={contains:name=>this.className.split(' ').includes(name),add:(...names)=>{this.className=[...new Set([...this.className.split(' ').filter(Boolean),...names])].join(' ')},remove:(...names)=>{this.className=this.className.split(' ').filter(n=>!names.includes(n)).join(' ')},toggle:(name,force)=>{const on=force??!this.classList.contains(name);on?this.classList.add(name):this.classList.remove(name);return on}};}
  append(...nodes){for(const node of nodes){node.remove();node.parentElement=this;this.children.push(node)}}appendChild(node){this.append(node);return node}remove(){if(context.document&&this.contains(context.document.activeElement))context.document.activeElement=body;if(this.parentElement)this.parentElement.children=this.parentElement.children.filter(n=>n!==this);this.parentElement=null}insertBefore(node,reference){node.remove();node.parentElement=this;const i=this.children.indexOf(reference);this.children.splice(i<0?this.children.length:i,0,node);return node}before(node){this.parentElement.insertBefore(node,this)}after(node){const next=this.nextSibling;this.parentElement.insertBefore(node,next)}get nextSibling(){const siblings=this.parentElement?.children||[];return siblings[siblings.indexOf(this)+1]||null}get parentNode(){return this.parentElement}get isConnected(){return this===body||Boolean(this.closest('body'))}contains(node){return node===this||this.children.some(child=>child.contains(node))}
  setAttribute(name,value){this.attributes.set(name,String(value));if(name==='hidden')this.hidden=true}getAttribute(name){return this.attributes.get(name)??null}removeAttribute(name){this.attributes.delete(name);if(name==='hidden')this.hidden=false}hasAttribute(name){return this.attributes.has(name)}
  matches(selector){return selector.split(',').some(raw=>{const s=raw.trim();if(s==='*')return true;if(s.startsWith('#'))return this.id===s.slice(1);if(s.startsWith('.'))return this.classList.contains(s.slice(1));if(s==='dialog[open]')return this.tagName==='DIALOG'&&this.open;if(s==='[hidden]')return this.hidden;if(s==='[id]')return Boolean(this.id);if(s==='[data-workspace-anchor]')return this.dataset.workspaceAnchor!==undefined;if(s==='[aria-current="page"]')return this.getAttribute('aria-current')==='page';return this.tagName===s.toUpperCase()})}closest(selector){for(let node=this;node;node=node.parentElement)if(node.matches(selector))return node;return null}querySelectorAll(selector){return this.children.flatMap(child=>[child,...child.querySelectorAll('*')]).filter(node=>node.matches(selector))}querySelector(selector){return this.querySelectorAll(selector)[0]||null}
  addEventListener(type,fn){register(this,type,fn)}focus(){document.activeElement=this;emit(document,'focusin',{target:this});if(topbar.contains(this))emit(topbar,'focusin',{target:this})}getBoundingClientRect(){return {top:0,bottom:this.height,height:this.height,width:390}}get offsetHeight(){return this.height}
 }
 const register=(target,type,fn)=>{const key=target===document?'document':target===window?'window':target;const item=listeners.get(key)||new Map();const handlers=item.get(type)||[];handlers.push(fn);item.set(type,handlers);listeners.set(key,item)};
 const emit=(target,type,event={})=>{const key=target===document?'document':target===window?'window':target;const e={target:target===document?body:target,type,preventDefault(){this.defaultPrevented=true},stopPropagation(){},...event};for(const fn of listeners.get(key)?.get(type)||[])fn(e);return e};
 const body=new Element('body'),html=new Element('html');html.append(body);const topbar=new Element('header','','topbar'),sidebar=new Element('aside','','sidebar'),navigation=new Element('section','workspace-navigation','workspace-navigation'),actions=new Element('div','topbar-actions','topbar-actions'),sectionsPanel=new Element('div','mobile-header-sections-panel'),morePanel=new Element('div','mobile-header-more-panel'),sections=new Element('button','mobile-header-sections'),more=new Element('button','mobile-header-more'),controls=new Element('div','mobile-header-controls');sectionsPanel.hidden=morePanel.hidden=true;body.append(topbar,sidebar);sidebar.append(navigation);topbar.append(controls,sectionsPanel,actions);controls.append(sections,more);navigation.append(new Element('a','nav-link'));actions.append(new Element('button','settings'));
 const document={body,documentElement:html,scrollingElement:html,activeElement:body,addEventListener(type,fn){register(this,type,fn)},querySelector:s=>html.querySelector(s),querySelectorAll:s=>html.querySelectorAll(s),getElementById:id=>html.querySelector('#'+id),createComment:()=>new Element('comment'),createElement:tag=>new Element(tag)};
 const media={matches:width<=720,addEventListener(type,fn){this.listener=fn},addListener(fn){this.listener=fn}};
 html.scrollHeight=body.scrollHeight=3000;body.dataset.workspaceView='build';
 const window={innerHeight:844,innerWidth:width,scrollY:0,pageYOffset:0,addEventListener(type,fn){register(this,type,fn)},matchMedia:()=>media};
 context={window,document,console,setTimeout(fn,delay){const id=nextTimer++;timers.set(id,{fn,at:now+delay});return id},clearTimeout(id){timers.delete(id)},store:{mode:'build'},location:{hash:''},innerWidth:width,matchMedia:()=>media,requestAnimationFrame:fn=>{frames.push(fn);return frames.length},cancelAnimationFrame(){},ResizeObserver:class{constructor(fn){this.fn=fn;observers.push(this)}observe(){}disconnect(){}},MutationObserver:class{observe(){}},getComputedStyle:()=>({display:'block',visibility:'visible'})};window.requestAnimationFrame=context.requestAnimationFrame;
 const drain=()=>{let turns=0;while(frames.length){assert.ok(turns++<20,'finite scheduled frames');frames.shift()()}};
 vm.createContext(context);vm.runInContext(read('mobile-header.js'),context);
 return {tick(ms){now+=ms;for(const [id,timer] of [...timers])if(timer.at<=now){timers.delete(id);timer.fn()}drain()},context,window,document,topbar,sidebar,navigation,actions,controls,sectionsPanel,morePanel,sections,more,media,observers,Element,emit,drain,scroll(y,target=document){window.scrollY=window.pageYOffset=y;emit(window,'scroll',{target});drain()},resize(next){context.innerWidth=window.innerWidth=next;media.matches=next<=720;media.listener?.({matches:media.matches});emit(window,'resize');drain()}};
}

const f=fixture(),api=f.window.DAWN_MOBILE_HEADER,hidden=()=>f.topbar.classList.contains('mobile-header-hidden');
assert.equal(f.navigation.parentElement,f.sidebar,'module is inert before explicit init');
api.init();const sameNavigation=f.navigation,sameActions=f.actions;assert.equal(f.navigation.parentElement,f.sectionsPanel);const sidebarNodes=f.sidebar.children.length;api.init();assert.equal(f.sidebar.children.length,sidebarNodes,'repeat init creates no second placeholder');assert.equal(f.actions.parentElement,f.topbar,'action nodes retain identity');assert.equal(f.controls.hidden,false);assert.equal(f.document.documentElement.style.values.get('--mobile-header-height'),'100px');
f.scroll(200);api.prepareNavigation();f.tick(140);f.scroll(223);assert.equal(hidden(),false,'23px down stays visible');f.scroll(224);assert.equal(hidden(),true,'24px down hides');f.scroll(213);assert.equal(hidden(),true,'11px up stays hidden');f.scroll(212);assert.equal(hidden(),false,'12px up reveals');
f.scroll(80);assert.equal(hidden(),false,'top always visible');f.scroll(110);assert.equal(hidden(),true,'24px accumulated downward after header boundary');f.scroll(105);assert.equal(hidden(),true,'5px upward jitter does not reveal');f.scroll(98);assert.equal(hidden(),false,'top reveals independently of upward threshold');
f.scroll(250);assert.equal(hidden(),true);f.scroll(244);assert.equal(hidden(),true);f.scroll(238);assert.equal(hidden(),false,'12px upward accumulation reveals');f.scroll(245);f.scroll(241);f.scroll(252);assert.equal(hidden(),false,'direction changes restart hysteresis');f.scroll(265);assert.equal(hidden(),true,'same-direction distance accumulates');
f.emit(f.sections,'click');assert.equal(f.sections.getAttribute('aria-expanded'),'true');assert.equal(f.sectionsPanel.hidden,false);assert.equal(hidden(),false);f.scroll(500);assert.equal(hidden(),false,'sections pins header');f.emit(f.more,'click');assert.equal(f.sectionsPanel.hidden,true);assert.equal(f.more.getAttribute('aria-expanded'),'true');assert.equal(sameActions.classList.contains('mobile-header-actions-open'),true);f.scroll(600);assert.equal(hidden(),false,'More pins header');f.emit(f.document,'keydown',{key:'Escape'});assert.equal(f.document.activeElement,f.more);assert.equal(f.more.getAttribute('aria-expanded'),'false');
f.emit(f.document,'pointerdown',{target:f.more});f.scroll(650);assert.equal(hidden(),true,'touch focus alone does not pin');f.emit(f.document,'keydown',{key:'Tab'});f.more.focus();assert.equal(hidden(),false,'keyboard focus reveals');f.scroll(700);assert.equal(hidden(),false,'keyboard focus pins');f.emit(f.document,'pointerdown',{target:f.document.body});f.scroll(750);assert.equal(hidden(),true,'outside pointer unpins');
const modal=new f.Element('dialog');modal.open=true;f.document.body.append(modal);f.scroll(800);assert.equal(hidden(),false,'native modal pins');modal.open=false;f.scroll(850);assert.equal(hidden(),true);api.prepareNavigation();assert.equal(hidden(),false);f.tick(140);f.scroll(920,f.navigation);assert.equal(hidden(),false,'nested scroll ignored');f.scroll(940);assert.equal(hidden(),true,'document scroll resumes after nested scroll');
api.prepareNavigation();f.scroll(1200);f.tick(100);f.scroll(1400);f.tick(100);assert.equal(hidden(),false,'smooth navigation scroll keeps header visible');f.tick(40);f.scroll(1430);assert.equal(hidden(),true,'user scroll after quiet release hides');
api.prepareNavigation();f.tick(140);f.scroll(-100);assert.equal(hidden(),false,'negative overscroll clamps to top');f.scroll(99999);assert.equal(hidden(),true);f.scroll(99999);f.scroll(2150);assert.equal(hidden(),true,'bottom overscroll does not accumulate phantom upward distance');f.scroll(2144);assert.equal(hidden(),false,'real upward movement from clamped bottom reveals');
f.emit(f.sections,'click');f.emit(f.document,'pointerdown',{target:f.document.body});assert.equal(f.sectionsPanel.hidden,true,'outside click closes menu');f.navigation.hidden=true;api.refresh();assert.equal(f.sections.hidden,true);f.navigation.hidden=false;api.refresh();assert.equal(f.sections.hidden,false);
f.scroll(1800);f.document.body.dataset.workspaceView='rules';api.refresh();assert.equal(hidden(),false,'mode refresh begins navigation visibility grace');f.tick(140);f.scroll(2200);assert.equal(hidden(),true);const anchor=f.navigation.children[0];anchor.dataset.workspaceAnchor='chapter';f.emit(f.sections,'click');f.emit(f.document,'click',{target:anchor});assert.equal(f.sectionsPanel.hidden,true,'anchor closes menu');f.scroll(1800);assert.equal(hidden(),false,'anchor jump remains visible');f.tick(140);
f.topbar.height=120;f.observers[0].fn();assert.equal(f.document.documentElement.style.values.get('--mobile-header-height'),'120px');assert.equal(f.document.documentElement.style.values.get('--mobile-header-visible-height'),'120px');f.resize(1440);assert.equal(f.navigation,sameNavigation);assert.equal(f.navigation.parentElement,f.sidebar,'desktop restores original navigation');assert.equal(f.actions,sameActions);assert.equal(f.controls.hidden,true);assert.equal(hidden(),false);assert.equal(f.document.documentElement.style.values.has('--mobile-header-height'),false);f.resize(720);assert.equal(f.navigation.parentElement,f.sectionsPanel,'720 is mobile');f.resize(721);assert.equal(f.navigation.parentElement,f.sidebar,'721 is desktop');
// Breakpoints must relocate focus as well as the same DOM nodes.
const focusedNav=fixture(1440);focusedNav.window.DAWN_MOBILE_HEADER.init();const toc=focusedNav.navigation.children[0];toc.focus();focusedNav.resize(390);assert.equal(focusedNav.document.activeElement,focusedNav.sections,'desktop TOC focus falls back to visible Sections on mobile');focusedNav.emit(focusedNav.sections,'click');toc.focus();focusedNav.resize(1440);assert.equal(focusedNav.document.activeElement,toc,'mobile TOC link regains focus after desktop reparent');
const focusedActions=fixture(1440);focusedActions.window.DAWN_MOBILE_HEADER.init();const settings=focusedActions.actions.children[0];settings.focus();focusedActions.resize(390);assert.equal(focusedActions.document.activeElement,focusedActions.more,'desktop action focus falls back to visible More on mobile');focusedActions.emit(focusedActions.more,'click');settings.focus();focusedActions.resize(1440);assert.equal(focusedActions.document.activeElement,settings,'mobile action regains focus after desktop disclosure closes');
const focusedControls=fixture(390);const activeMode=new focusedControls.Element('button','mode-tools');activeMode.setAttribute('aria-current','page');focusedControls.topbar.append(activeMode);focusedControls.window.DAWN_MOBILE_HEADER.init();focusedControls.sections.focus();focusedControls.resize(1440);assert.equal(focusedControls.document.activeElement,activeMode,'hidden mobile disclosure returns focus to desktop mode');
const html=read('index.html'),sw=read('sw.js'),qa=read('tests/qa.mjs'),app=read('app.js'),css=read('mobile-header.css');
for(const asset of ['mobile-header.js','mobile-header.css']){assert.ok(html.includes(asset),'HTML links '+asset);assert.ok(sw.includes(asset),'offline cache links '+asset)}assert.ok(qa.includes('mobile-header.js'),'QA runtime loads controller');assert.match(app,/DAWN_MOBILE_HEADER.*init|MobileHeader.*init/s,'app explicitly initializes controller');assert.match(css,/prefers-reduced-motion/,'motion preference supported');
console.log('Mobile header VM scenarios passed: node placement, desktop restore, scroll hysteresis/clamp, keyboard/touch, menus/dialog, mode/anchor quiet period, measurement and asset linkage. Browser CSS layout not exercised.');
