/* Isolated design demo. Only DAWN_LOGIC pure functions are shared with production. */
const variant = ['1','2','3'].includes(new URLSearchParams(location.search).get('variant')) ? new URLSearchParams(location.search).get('variant') : '1';
document.body.classList.add(`variant-${variant}`);
document.querySelector(`.variants a[href="?variant=${variant}"]`).classList.add('active');
const heroes = {
  nari:{id:'nari',name:'Нари',player:'Ксения',initial:'Н',tier:2,attrs:{body:5,talent:2,spirit:4,mind:2},hp:10,maxHp:19,focus:2,influence:1,skills:[['Боец из засады',3],['Мастер ловушек',2],['Паркур',2]],abilities:[['Стать призраком',2]],bonds:[['Икар · Партнёр',1],['Рен Эмбер · Подопечный',2]],gearhead:false},
  neel:{id:'neel',name:'Неель',player:'Никита',initial:'Н',tier:2,attrs:{body:2,talent:2,spirit:4,mind:5},hp:16,maxHp:16,focus:2,influence:1,skills:[['Наука',3],['Оперативник',2]],abilities:[['Манипулировать магией',1]],bonds:[['Красная Звезда · Команда',1]],gearhead:true},
  ren:{id:'ren',name:'Рен Эмбер',player:'Игрок',initial:'Р',tier:2,attrs:{body:2,talent:4,spirit:5,mind:2},hp:12,maxHp:16,focus:3,influence:1,skills:[['Медицина',3],['Наблюдательность',2]],abilities:[['Исцелять людей',3]],bonds:[['Нари · Наставница',2]],gearhead:false}
};
const attrs={body:'Тело',talent:'Талант',spirit:'Дух',mind:'Разум'};
const state={hero:'nari',role:'player',attr:'body',skill:0,ability:-1,bond:-1,adv:0,hind:0,target:2,result:null,pending:null,notice:'',history:[],clock:2,groupTask:'roll',gadgetEnabled:true};
const app=document.querySelector('#app');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function hero(){return heroes[state.hero]}
function abilityOptions(){return hero().abilities.concat(hero().gearhead&&state.gadgetEnabled?[['Гаджет · Портативный сканер',1],['Гаджет · Полевой генератор',1],['Гаджет · Магический резонатор',1]]:[])}
function poolParts(){const h=hero(),a=abilityOptions();return [[attrs[state.attr],h.attrs[state.attr]],[h.skills[state.skill]?.[0]||'Навык',h.skills[state.skill]?.[1]||0],[a[state.ability]?.[0]||'Способность',a[state.ability]?.[1]||0],[h.bonds[state.bond]?.[0]||'Связь',h.bonds[state.bond]?.[1]||0],['Преимущество',state.adv],['Помеха',-state.hind]]}
function pool(){return Math.max(1,poolParts().reduce((n,p)=>n+p[1],0))}
function options(items,selected,empty){return `${empty?`<option value="-1" ${selected===-1?'selected':''}>${empty}</option>`:''}`+items.map((p,i)=>`<option value="${i}" ${i===selected?'selected':''}>${esc(p[0])} · ${p[1]}</option>`).join('')}
function resources(h){return `<div class="resources"><div class="resource"><span>Здоровье</span><strong>${h.hp}<em> / ${h.maxHp}</em></strong></div><div class="resource"><span>Фокус</span><strong>${h.focus}</strong></div><div class="resource"><span>Влияние</span><strong>${h.influence}</strong></div></div>`}
function heroSelect(){return `<select class="hero-select" aria-label="Активный герой" data-field="hero">${Object.values(heroes).map(h=>`<option value="${h.id}" ${h.id===state.hero?'selected':''}>${h.name} · ${h.player}</option>`).join('')}</select>`}
function attributes(){return `<div class="attributes" aria-label="Атрибут броска">${Object.entries(attrs).map(([id,label])=>`<button class="attr ${id===state.attr?'active':''}" data-action="attr" data-value="${id}" aria-pressed="${id===state.attr}">${label}<b>${hero().attrs[id]}</b></button>`).join('')}</div>`}
function header(){return `<header class="app-header"><a class="brand" href="../../index.html?mode=build&edition=lionwing&lang=ru"><span class="brand-mark">✦</span> DAWN</a><span class="edition">LIONWING</span><nav class="nav" aria-label="Основная навигация">${[['build','Герой'],['tools','Инструменты'],['play','Стол'],['rules','Правила'],['reference','Справочник']].map(([mode,label])=>`<a ${mode==='tools'?'class="current" aria-current="page" href="#app"':`href="../../index.html?mode=${mode}&edition=lionwing&lang=ru"`}>${label}</a>`).join('')}</nav><span class="room"><i class="dot"></i>Локальный макет</span></header>`}
function heading(){return `<div class="page-heading"><div><h1>${variant==='3'?'Красная Звезда':'Инструменты'}</h1><p>${variant==='1'?'Бросок, ресурсы и история — в одном рабочем месте.':variant==='2'?'Соберите действие. Бросьте кости. Продолжайте историю.':'Два героя, общие запросы и ход истории.'}</p></div><div class="role"><label for="role">Роль</label><select id="role" data-field="role"><option value="player" ${state.role==='player'?'selected':''}>Игрок</option><option value="narrator" ${state.role==='narrator'?'selected':''}>Нарратор</option></select></div></div>`}
function stepper(label,field){return `<div class="stepper"><span>${label}</span><button data-action="step" data-value="${field}:-1" aria-label="Уменьшить ${label.toLowerCase()}" ${state[field]===0?'disabled':''}>−</button><output>${state[field]}</output><button data-action="step" data-value="${field}:1" aria-label="Увеличить ${label.toLowerCase()}" ${state[field]>=12?'disabled':''}>+</button></div>`}
function requestPanel(){if(state.role==='narrator')return `<div class="request-editor"><label class="field"><span>Что предстоит сделать?</span><input id="request-text" value="Пробраться через дозор" maxlength="120"></label><label class="field"><span>Риск при Провале</span><input id="risk-text" value="Поднять тревогу" maxlength="120"></label><button data-action="request">Запросить у ${hero().name}</button></div>`;if(state.pending)return `<div class="request"><div><p class="eyebrow">Запрос Нарратора</p><strong>${esc(state.pending.text)}</strong><p>Цель ${state.target} · Риск: ${esc(state.pending.risk)}</p></div><button data-action="cancel-request" aria-label="Отклонить демонстрационный запрос">Отклонить</button></div>`;return ''}
function fields(){const grid=variant==='2'?'sentence':'field-grid';return `<div class="${grid}">${variant==='2'?`<label class="field"><span>Действую через…</span><select data-field="attr" aria-label="Атрибут">${Object.entries(attrs).map(([id,name])=>`<option value="${id}" ${state.attr===id?'selected':''}>${name} · ${hero().attrs[id]}</option>`).join('')}</select></label>`:''}<label class="field"><span>${variant==='2'?'Использую…':'Навык'}</span><select data-field="skill" aria-label="Навык">${options(hero().skills,state.skill,'Без Навыка')}</select></label><label class="field"><span>${variant==='2'?'И применяю…':hero().gearhead&&state.gadgetEnabled?'Способность или гаджет':'Способность'}</span><select data-field="ability" aria-label="Способность или гаджет">${options(abilityOptions(),state.ability,'Без Способности')}</select></label><label class="field ${variant==='2'?'wide':''}"><span>Опираюсь на Связь</span><select data-field="bond" aria-label="Связь">${options(hero().bonds,state.bond,'Без Связи')}</select></label>${variant==='2'?'':`<div class="field"><span>Атрибут</span><div class="tag"><b>${attrs[state.attr]}</b> ${hero().attrs[state.attr]} костей</div><small>Выберите в панели героя.</small></div>`}</div>`}
function result(){if(!state.result)return `<div class="result empty" aria-live="polite">Результат появится здесь после броска.</div>`;const r=state.result;return `<div class="result" aria-live="polite"><div class="result-heading"><strong>${r.successes} Успехов · ${esc(r.outcome.label)}</strong><span>Цель ${r.target} · Крайний ${r.target*2}</span></div><div class="dice" aria-label="Выпавшие кости: ${r.rolls.join(', ')}">${r.rolls.map(n=>`<span class="die ${n>=r.threshold?'success':''} ${n===6?'crit':''}">${n}</span>`).join('')}</div><div class="result-foot"><span>${r.count}D6 · Успехи ${r.threshold}+ · ${r.crits} Критов${r.allIn?' · −1 Влияние':''}</span><button data-action="allin" ${r.allIn||hero().influence<1?'disabled':''}>Ва-банк · 1 Влияние</button></div>${hero().influence<1&&!r.allIn?'<p class="notice">Нет Влияния для Ва-банк.</p>':''}</div>`}
function composer(){return `<section class="panel composer" aria-label="Сборка броска"><div class="composer-head"><div><p class="eyebrow">${state.pending?'Испытание':'Свободный бросок'}</p><h2>${variant==='2'?'Как вы это сделаете?':state.pending?esc(state.pending.text):'Что делает герой?'}</h2></div><button class="ghost small" data-action="help" aria-label="Правила броска">? Правила</button></div>${requestPanel()}${fields()}<div class="adjustments">${stepper('Преимущество','adv')}${stepper('Помеха','hind')}</div><div class="roll-strip"><div class="pool" aria-live="polite">${pool()}<small>D6</small></div><p class="breakdown">${poolParts().filter(p=>p[1]).map(p=>`${esc(p[0])} ${p[1]>0?'+':''}${p[1]}`).join(' · ')}</p><label class="target">Цель Успехов <input type="number" min="1" max="20" value="${state.target}" data-field="target" aria-label="Цель Успехов"></label></div><div class="roll-actions"><button class="primary" data-action="roll">${state.pending?'Ответить на запрос':'Бросить'} ${pool()}D6 <span aria-hidden="true">↗</span></button><button class="ghost small" data-action="reset">Сбросить выбор</button></div>${state.notice?`<p class="notice" role="status">${esc(state.notice)}</p>`:''}${result()}</section>`}
function history(){return `<section class="panel"><div class="side-head"><h3>${variant==='3'?'Общий журнал':'Последние броски'}</h3><span>${state.history.length} записей</span></div>${state.history.length?`<ol class="history">${state.history.slice(0,4).map(r=>`<li><strong>${esc(r.name)}</strong><div class="meta"><span>${r.count}D6 → ${r.successes} Успехов</span><span>${r.time}</span></div><div class="mini-dice">${r.rolls.slice(0,16).join(' ')}</div><span class="outcome">${esc(r.outcome.label)}${r.allIn?' · Ва-банк':''}</span></li>`).join('')}</ol>`:'<p class="empty-feed">Здесь останется результат каждого броска этой сессии макета.</p>'}</section>`}
function clock(){return `<div class="clock-row"><div><strong>Тревога в лагере</strong><span>${state.clock} из 6 · часы Нарратора</span><div class="segments" aria-label="Часы: ${state.clock} из 6">${Array.from({length:6},(_,i)=>`<i class="${i<state.clock?'done':''}"></i>`).join('')}</div></div><button data-action="clock" aria-label="Продвинуть часы тревоги" ${state.role!=='narrator'||state.clock===6?'disabled':''}>+</button></div>`}
function supports(){return `<section class="panel"><div class="side-head"><h3>Рядом с броском</h3></div><div class="clock-list">${clock()}</div><details class="support"><summary>Связи героя</summary><div class="bonds">${hero().bonds.map(b=>`<span class="tag">${esc(b[0])} <b>${b[1]}</b></span>`).join('')}</div></details></section>`}
function demo(){return `<details class="demo-options"><summary>Проверить условные элементы макета</summary><label><input type="checkbox" data-field="gadgetEnabled" ${state.gadgetEnabled?'checked':''}>Неель обладает особенностью с гаджетами</label><p>Выберите Нееля, затем включите или выключите особенность: варианты гаджетов появятся или исчезнут из сборки броска.</p></details>`}
function heroPanel(){return `<aside class="rail"><section class="panel"><div class="hero-head"><span class="avatar">${hero().initial}</span><div><strong>${hero().name}</strong><small>Ступень ${hero().tier} · ${hero().player}</small></div></div>${heroSelect()}${resources(hero())}<p class="rail-title" style="margin-top:22px">АТРИБУТ БРОСКА</p>${attributes()}</section><p class="rail-note">Изменения в макете живут до перезагрузки страницы.</p></aside>`}
function render(){const active=document.activeElement,focusKey=active?.dataset.field?`[data-field="${active.dataset.field}"]`:active?.dataset.action?`[data-action="${active.dataset.action}"]${active.dataset.value?`[data-value="${active.dataset.value}"]`:""}`:null;let body;if(variant==='1')body=`<div class="workspace">${heroPanel()}<div>${composer()}${demo()}</div><aside class="aside rail">${history()}${supports()}</aside></div>`;else if(variant==='2')body=`<div class="line-workspace"><div><div class="line-hero"><span class="avatar">${hero().initial}</span>${heroSelect()}${resources(hero())}</div>${composer()}${demo()}</div><aside class="aside">${history()}${supports()}</aside></div>`;else body=`<div class="group-top">${['nari','neel'].map(id=>`<button class="group-card ${id===state.hero?'active':''}" data-action="hero" data-value="${id}" aria-pressed="${id===state.hero}">${id===state.hero?'<span class="selected-label">Выбран</span>':''}<span class="avatar">${heroes[id].initial}</span><div><strong>${heroes[id].name}</strong><small>${heroes[id].player} · Ступень 2</small></div>${resources(heroes[id])}</button>`).join('')}<section class="group-card support-card">${clock()}</section></div><div class="group-workspace"><aside class="rail"><div class="task-switch"><button class="${state.groupTask==='roll'?'active':''}" data-action="task" data-value="roll">Бросок</button><button class="${state.groupTask==='request'?'active':''}" data-action="task" data-value="request">Запрос</button><button class="${state.groupTask==='bonds'?'active':''}" data-action="task" data-value="bonds">Связи</button></div>${attributes()}${state.groupTask==='bonds'?`<div class="support"><h3>Связи ${hero().name}</h3><div class="bonds">${hero().bonds.map((b,i)=>`<button class="tag" data-action="bond" data-value="${i}">${esc(b[0])} <b>${b[1]}</b></button>`).join('')}</div></div>`:''}</aside><div>${composer()}${demo()}</div><aside class="aside rail">${history()}${supports()}</aside></div>`;app.innerHTML=`<div class="shell">${header()}${heading()}${body}<footer class="page-note"><span>${['','01 / Рабочее место','02 / Строка действия','03 / Пульт группы'][variant]} · HTML-черновик от 6 октября 2026</span><a href="README.md">Проверенные сценарии и границы макета ↗</a></footer></div>`;if(focusKey)app.querySelector(focusKey)?.focus({preventScroll:true})}
function changeHero(id){state.hero=id;state.attr=id==='nari'?'body':'mind';state.skill=0;state.ability=-1;state.bond=-1;state.result=null;state.pending=null;state.notice=''}
function roll(allIn=false){if(allIn&&(!state.result||state.result.allIn||hero().influence<1))return;const count=allIn?state.result.count:pool(),target=allIn?state.result.target:state.target,threshold=allIn?3:4;const r=window.DAWN_LOGIC.rollXd6({count,threshold});if(allIn)hero().influence--;state.result={...r,count,target,threshold,allIn,outcome:window.DAWN_LOGIC.challengeOutcome({successes:r.successes,target}),name:hero().name,time:new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})};state.history.unshift(state.result);state.pending=null;state.notice='';render()}
app.addEventListener('change',e=>{const f=e.target.dataset.field;if(!f)return;if(f==='hero')changeHero(e.target.value);else if(f==='gadgetEnabled'){state.gadgetEnabled=e.target.checked;if(state.ability>=hero().abilities.length)state.ability=-1}else if(f==='role'){state.role=e.target.value;state.groupTask='roll';state.pending=null}else{state[f]=['attr'].includes(f)?e.target.value:Math.max(f==='target'?1:-1,Math.min(f==='target'?20:99,Number(e.target.value)));state.notice=''}render()});
app.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,v=b.dataset.value;if(a==='help'){document.querySelector('#help').showModal();return}if(a==='roll'){roll();return}if(a==='allin'){roll(true);return}if(a==='attr')state.attr=v;if(a==='hero')changeHero(v);if(a==='bond')state.bond=Number(v);if(a==='step'){const[f,n]=v.split(':');state[f]=Math.max(0,Math.min(12,state[f]+Number(n)))}if(a==='clock')state.clock=Math.min(6,state.clock+1);if(a==='reset'){state.skill=-1;state.ability=-1;state.bond=-1;state.adv=0;state.hind=0;state.notice='Выбор источников сброшен.'}if(a==='cancel-request'){state.pending=null;state.notice='Запрос отклонён в макете.'}if(a==='request'){state.pending={text:document.querySelector('#request-text').value.trim()||'Испытание',risk:document.querySelector('#risk-text').value.trim()||'Риск не указан'};state.role='player';state.groupTask='roll';state.notice=`Запрос создан для ${hero().name}. Теперь показан ответ игрока.`}if(a==='task'){state.groupTask=v;if(v==='request')state.role='narrator';else state.role='player'}render()});
document.querySelector('#help').addEventListener('click',e=>{if(e.target===e.currentTarget)e.currentTarget.close()});
render();
