"use strict";

let pendingGmVariantTokenImage="";

function gmLibrary(){
  if(!store.gmLibrary)store.gmLibrary=normalizeGmLibrary(null);
  return store.gmLibrary;
}

function enemyActorFromProfile(profile,tier,{variant=null,blueprint=null,spaceId=Scene.activeSpace,position=null}={}){
  const stats=scaledEnemyStats(profile,tier),overrides=variant?.overrides||{},source=blueprint||{},effectIds=blueprint?.effects||(profile.deployEffects||[]).map(name=>D.effects.positive.concat(D.effects.negative).find(effect=>effect.name===name)?.id||name),baseAp=blueprint?Number(source.baseAp||2):Number(overrides.ap??2),maxHp=blueprint?Number(source.maxHp||1):Number(overrides.health??stats.health),cell=position||firstEmptyCell(spaceId);
  return {id:uid(),kind:"enemy",team:"enemy",heroId:null,profileId:profile.id,enemyVariantId:blueprint?.enemyVariantId||variant?.id||null,gmRole:blueprint?.gmRole||variant?.role||null,notes:blueprint?.notes||variant?.notes||"",name:blueprint?.name||variant?.name||profile.name,tier,space:spaceId,...cell,hp:blueprint?Math.min(Number(source.hp??maxHp),maxHp):maxHp,maxHp,focus:0,ap:blueprint?Number(source.ap??baseAp):baseAp,baseAp,speed:blueprint?Number(source.speed||0):Number(overrides.speed??stats.speed),armor:blueprint?Number(source.armor||0):Number(overrides.armor??stats.armor),evasion:blueprint?Number(source.evasion||0):Number(overrides.evasion??stats.evasion),effects:[...effectIds],usedActions:[],usedTrump:false,acted:false,hidden:false,tokenSymbol:blueprint?.tokenSymbol||variant?.tokenSymbol||"☠",tokenColor:blueprint?.tokenColor||variant?.tokenColor||"#902a3d",tokenImage:blueprint?.tokenImage||variant?.tokenImage||profile.tokenImage||"",portraitImage:blueprint?.portraitImage||variant?.portraitImage||""};
}

function encounterBlueprint(actor){
  return {profileId:actor.profileId,enemyVariantId:actor.enemyVariantId||null,name:actor.name,tier:actor.tier,x:actor.x,y:actor.y,hp:actor.hp,maxHp:actor.maxHp,ap:actor.ap,baseAp:actor.baseAp,speed:actor.speed,armor:actor.armor,evasion:actor.evasion,effects:[...(actor.effects||[])],tokenSymbol:actor.tokenSymbol,tokenColor:actor.tokenColor,tokenImage:actor.tokenImage||"",portraitImage:actor.portraitImage||"",gmRole:actor.gmRole||"named",notes:actor.notes||""};
}

function availableEncounterCell(space,wanted,occupied){
  const start={x:clamp(wanted?.x,0,space.width-1),y:clamp(wanted?.y,0,space.height-1)};
  for(let distance=0;distance<space.width+space.height;distance++)for(let y=0;y<space.height;y++)for(let x=0;x<space.width;x++)if(Math.abs(x-start.x)+Math.abs(y-start.y)===distance&&!occupied.has(`${x},${y}`)){occupied.add(`${x},${y}`);return{x,y}}
  return null;
}

function resetGmVariantEditor(){
  $("gm-enemy-variant-id").value="";$("gm-enemy-name").value="";$("gm-enemy-role").value="named";$("gm-enemy-tier").value="1";$("gm-enemy-symbol").value="☠";$("gm-enemy-color").value="#902a3d";for(const id of ["health","speed","armor","evasion","ap"])$(`gm-enemy-${id}`).value="";$("gm-enemy-notes").value="";$("gm-enemy-token-upload").value="";pendingGmVariantTokenImage="";$("gm-enemy-token-preview").hidden=true;$("gm-cancel-enemy-variant").hidden=true;$("gm-save-enemy-variant").textContent="Сохранить в библиотеку";
}

function editGmVariant(variant){
  if(!variant)return;$("gm-enemy-variant-id").value=variant.id;$("gm-enemy-name").value=variant.name;$("gm-enemy-role").value=variant.role;$("gm-enemy-tier").value=variant.tier;$("gm-enemy-profile").value=variant.baseProfileId;$("gm-enemy-symbol").value=variant.tokenSymbol;$("gm-enemy-color").value=variant.tokenColor;for(const id of ["health","speed","armor","evasion","ap"])$(`gm-enemy-${id}`).value=variant.overrides[id]??"";$("gm-enemy-notes").value=variant.notes;pendingGmVariantTokenImage=variant.tokenImage||"";const preview=$("gm-enemy-token-preview");preview.hidden=!pendingGmVariantTokenImage;preview.innerHTML=pendingGmVariantTokenImage?`<img src="${pendingGmVariantTokenImage}" alt="Токен ${esc(variant.name)}">`:"";$("gm-cancel-enemy-variant").hidden=false;$("gm-save-enemy-variant").textContent="Сохранить изменения";$("gm-enemy-name").focus();
}

function renderGmLibraries(){
  const profileSelect=$("gm-enemy-profile");if(!profileSelect)return;const previous=profileSelect.value||$("scene-enemy-select")?.value,profiles=[...(D.enemies?.named||[]),...(D.enemies?.common||[]),...(D.enemies?.modifiers||[])];profileSelect.innerHTML=profiles.map(profile=>`<option value="${esc(profile.id)}">${esc(profile.name)} · ${esc(profile.tags||"")}</option>`).join("");if(profiles.some(profile=>profile.id===previous))profileSelect.value=previous;
  const roleName={named:"Именной",boss:"Босс",npc:"НПС"},library=gmLibrary();
  $("gm-enemy-library").innerHTML=library.enemyVariants.map(variant=>{const profile=enemyProfile(variant.baseProfileId),id=esc(variant.id);return `<article class="gm-library-card"><div class="gm-library-token" style="--token-color:${variant.tokenColor}">${variant.tokenImage?`<img src="${variant.tokenImage}" alt="">`:esc(variant.tokenSymbol||"☠")}</div><div><strong>${esc(variant.name)}</strong><small>${roleName[variant.role]} · ${esc(profile?.name||"Профиль удалён")} · Ст. ${variant.tier}</small></div><div class="gm-library-actions"><button type="button" data-gm-variant-add="${id}" class="primary">На поле</button><button type="button" data-gm-variant-edit="${id}">Править</button><button type="button" data-gm-variant-delete="${id}" aria-label="Удалить">×</button></div></article>`}).join("")||`<p class="autosave">Сохранённых именных противников пока нет.</p>`;
  $("gm-encounter-library").innerHTML=library.encounters.map(encounter=>{const id=esc(encounter.id);return `<article class="gm-encounter-card"><div><strong>${esc(encounter.name)}</strong><small>${encounter.enemies.length} врагов · поле ${encounter.width}×${encounter.height}</small></div><div class="gm-library-actions"><button type="button" data-gm-encounter-deploy="${id}" class="primary">Развернуть</button><button type="button" data-gm-encounter-reinforce="${id}">Подкрепление</button><button type="button" data-gm-encounter-delete="${id}" aria-label="Удалить">×</button></div></article>`}).join("")||`<p class="autosave">Сохранённых расстановок пока нет.</p>`;
}

function deployEncounter(encounter,{replace=false}={}){
  if(!encounter)return;if(Scene.activeActorId||Scene.pendingAction||Scene.pendingActionPlan)return toast("Сначала завершите текущий Ход или действие");const space=activeSceneSpace();let placed=0;commitScene(`${replace?"Развёрнуто":"Добавлено подкрепление"}: ${encounter.name}`,scene=>{if(replace){const removed=new Set(scene.actors.filter(actor=>actor.space===space.id&&actor.team==="enemy"&&actor.profileId).map(actor=>actor.id));scene.actors=scene.actors.filter(actor=>!removed.has(actor.id));scene.selectedActor=null;scene.targetIds=scene.targetIds.filter(id=>!removed.has(id));scene.round=1;scene.tension=0;space.width=clamp(encounter.width,1,12);space.height=clamp(encounter.height,1,12);scene.actors.filter(actor=>actor.space===space.id).forEach(actor=>{actor.x=clamp(actor.x,0,space.width-1);actor.y=clamp(actor.y,0,space.height-1)});scene.actors.forEach(actor=>{actor.acted=false;actor.ap=actor.baseAp;actor.usedActions=[];actor.usedTrump=false})}const occupied=new Set(scene.actors.filter(actor=>actor.space===space.id&&!actor.knockedOut).map(actor=>`${actor.x},${actor.y}`));for(const blueprint of encounter.enemies){const profile=enemyProfile(blueprint.profileId);if(!profile)continue;const position=availableEncounterCell(space,blueprint,occupied);if(!position)continue;scene.actors.push(enemyActorFromProfile(profile,blueprint.tier,{blueprint,spaceId:space.id,position}));placed+=1}});toast(`${encounter.name}: ${placed} врагов готовы${placed<encounter.enemies.length?", остальным не хватило свободных клеток":""}`);
}

const baseRenderSceneInspectorGmLibrary=renderSceneInspector;
renderSceneInspector=function(){baseRenderSceneInspectorGmLibrary();const actor=Scene.actors.find(item=>item.id===Scene.selectedActor),settings=$("scene-inspector")?.querySelector(".scene-inspector-settings-body");if(actor?.team==="enemy"&&actor.profileId&&settings)settings.insertAdjacentHTML("beforeend",`<button type="button" class="primary save-enemy-library" data-save-enemy-to-library="${actor.id}">Сохранить как именного противника</button>`)};

$("gm-enemy-token-upload").addEventListener("change",async event=>{const file=event.target.files?.[0];if(!file)return;try{pendingGmVariantTokenImage=await tokenImageFromFile(file);const preview=$("gm-enemy-token-preview");preview.hidden=false;preview.innerHTML=`<img src="${pendingGmVariantTokenImage}" alt="Предпросмотр токена">`}catch(error){toast(error.message)}});
$("gm-cancel-enemy-variant").onclick=resetGmVariantEditor;
$("gm-save-enemy-variant").onclick=()=>{const profile=enemyProfile($("gm-enemy-profile").value),name=$("gm-enemy-name").value.trim();if(!profile)return toast("Выберите базовый профиль");if(!name)return toast("Назовите противника");const numberOrNull=id=>{const value=$(`gm-enemy-${id}`).value;return value===""?null:Number(value)},id=$("gm-enemy-variant-id").value||uid(),variant={id,name,baseProfileId:profile.id,tier:clamp($("gm-enemy-tier").value,1,99),role:$("gm-enemy-role").value,tokenSymbol:$("gm-enemy-symbol").value.trim().slice(0,4)||"☠",tokenColor:$("gm-enemy-color").value,tokenImage:pendingGmVariantTokenImage,portraitImage:"",notes:$("gm-enemy-notes").value.trim(),overrides:{health:numberOrNull("health"),speed:numberOrNull("speed"),armor:numberOrNull("armor"),evasion:numberOrNull("evasion"),ap:numberOrNull("ap")}},index=gmLibrary().enemyVariants.findIndex(item=>item.id===id);if(index>=0)gmLibrary().enemyVariants[index]=variant;else gmLibrary().enemyVariants.unshift(variant);store.gmLibrary=normalizeGmLibrary(store.gmLibrary);persist();resetGmVariantEditor();renderGmLibraries();toast(`${name} сохранён в библиотеке`)};
$("gm-enemy-library").onclick=event=>{const add=event.target.closest("[data-gm-variant-add]"),edit=event.target.closest("[data-gm-variant-edit]"),remove=event.target.closest("[data-gm-variant-delete]"),id=add?.dataset.gmVariantAdd||edit?.dataset.gmVariantEdit||remove?.dataset.gmVariantDelete,variant=gmLibrary().enemyVariants.find(item=>item.id===id);if(add&&variant){const profile=enemyProfile(variant.baseProfileId);if(!profile)return toast("Базовый профиль больше не существует");commitScene(`Добавлен именной противник «${variant.name}»`,scene=>{const actor=enemyActorFromProfile(profile,variant.tier,{variant,spaceId:scene.activeSpace});scene.actors.push(actor);scene.selectedActor=actor.id});return}if(edit){editGmVariant(variant);return}if(remove){gmLibrary().enemyVariants=gmLibrary().enemyVariants.filter(item=>item.id!==id);persist();renderGmLibraries();toast("Именной противник удалён из библиотеки")}};
$("gm-save-encounter").onclick=()=>{const space=activeSceneSpace(),enemies=Scene.actors.filter(actor=>actor.space===space.id&&actor.team==="enemy"&&actor.profileId),name=$("gm-encounter-name").value.trim();if(!enemies.length)return toast("На текущем поле нет профильных врагов");if(!name)return toast("Назовите расстановку");gmLibrary().encounters.unshift({id:uid(),name,createdAt:new Date().toISOString(),width:space.width,height:space.height,enemies:enemies.map(encounterBlueprint)});store.gmLibrary=normalizeGmLibrary(store.gmLibrary);$("gm-encounter-name").value="";persist();renderGmLibraries();toast(`Расстановка «${name}» сохранена`)};
$("gm-encounter-library").onclick=event=>{const deploy=event.target.closest("[data-gm-encounter-deploy]"),reinforce=event.target.closest("[data-gm-encounter-reinforce]"),remove=event.target.closest("[data-gm-encounter-delete]"),id=deploy?.dataset.gmEncounterDeploy||reinforce?.dataset.gmEncounterReinforce||remove?.dataset.gmEncounterDelete,encounter=gmLibrary().encounters.find(item=>item.id===id);if(deploy){deployEncounter(encounter,{replace:true});return}if(reinforce){deployEncounter(encounter);return}if(remove){gmLibrary().encounters=gmLibrary().encounters.filter(item=>item.id!==id);persist();renderGmLibraries();toast("Расстановка удалена")}};
$("scene-inspector").addEventListener("click",event=>{const button=event.target.closest("[data-save-enemy-to-library]");if(!button)return;const actor=Scene.actors.find(item=>item.id===button.dataset.saveEnemyToLibrary),profile=enemyProfile(actor?.profileId);if(!actor||!profile)return;const existing={id:actor.enemyVariantId||uid(),name:actor.name,baseProfileId:profile.id,tier:actor.tier,role:actor.gmRole||"named",tokenSymbol:actor.tokenSymbol,tokenColor:actor.tokenColor,tokenImage:actor.tokenImage,portraitImage:actor.portraitImage,notes:actor.notes||"",overrides:{health:actor.maxHp,speed:actor.speed,armor:actor.armor,evasion:actor.evasion,ap:actor.baseAp}};editGmVariant(existing);setScenePanel("add",true);toast("Параметры перенесены в библиотеку — проверьте и сохраните")});
