"use strict";

function renderSidebar(){
  const d=derived(),b=budgets(),en=isEnglishPreview(); ensureRuntime();
  $("derived").innerHTML=(en?[["Health",d.hp],["Guts",d.guts],["Speed",d.speed],["Focus",d.focus]]:[["Здоровье",d.hp],["Стойкость",d.guts],["Скорость",d.speed],["Фокус",d.focus]]).map(([n,v])=>`<div class="derived"><span>${n}</span><strong>${v}</strong></div>`).join("");
  $("budgets").innerHTML=budgetRow(en?"Attributes":"Атрибуты",b.attrSpent,b.attrPool)+budgetRow(en?"Boons":"Дары",b.giftSpent,b.giftPool)+budgetRow(en?"Ranks":"Ранги",b.rankSpent,b.rankPool,Boolean(b.rankOver||b.taintedAbilityOver||b.rankBudgetConflict))+budgetRow(en?"Techniques":"Техники",b.techSpent,b.techPool);
  const list=issues();$("warnings").innerHTML=list.map(([kind,text])=>`<div class="warning ${kind}">${esc(en?"Russian mechanics validation requires review. Switch to RU for details.":text)}</div>`).join("")||`<div class="warning" style="border-color:var(--good)">${en?"Build matches the current mechanical budgets.":"Сборка согласована с базовыми бюджетами."}</div>`;
  const completed=[S.name.trim(),Object.values(S.attrs).sort().join(",")==="2,2,3,4",S.primaryOutlook,b.giftSpent===b.giftPool,b.skillSpent>=b.skillMin,b.rankOver===0&&!b.taintedAbilityOver&&!b.rankBudgetConflict,b.techSpent===b.techPool].filter(Boolean).length;
  $("build-progress").textContent=en?`${completed}/7 key steps · Russian mechanics ${list.some(i=>i[0]==="bad")?"need review":"are valid"}`:`${completed}/7 ключевых шагов · ${list.filter(i=>i[0]==="bad").length?"нужна проверка":"механика сходится"}`;
}
function renderHeroSelect(){
  $("hero-select").innerHTML=store.heroes.map((h,i)=>`<option value="${i}" ${i===store.current?"selected":""}>${esc(h.name||(isEnglishPreview()?"Unnamed":"Безымянный"))} · ${isEnglishPreview()?"Tier":"Ст."}${h.tier}</option>`).join("");
  if($("scene-hero-select")){const previous=$("scene-hero-select").value;$("scene-hero-select").innerHTML=store.heroes.map(h=>`<option value="${h.id}">${esc(h.name||"Безымянный")} · Ст.${h.tier}</option>`).join("");$("scene-hero-select").value=store.heroes.some(h=>h.id===previous)?previous:S.id}
}
function renderProfile(){const en=isEnglishPreview(),hero=S.name||(en?"hero":"героя");for(const key of ["name","player","concept"])$("f-"+key).value=S[key];$("f-tier").value=S.tier;$("hero-portrait-preview").innerHTML=S.media.portrait?`<img src="${S.media.portrait}" alt="${en?"Portrait of":"Портрет"} ${esc(hero)}">`:`<span>${en?"Portrait":"Портрет"}</span>`;$("hero-token-preview").innerHTML=S.media.token?`<img src="${S.media.token}" alt="${en?"Token of":"Токен"} ${esc(hero)}">`:`<span>${en?"Token":"Токен"}</span>`;$("hero-portrait-clear").disabled=!S.media.portrait;$("hero-token-clear").disabled=!S.media.token}
function renderAttrs(){
  const maxBonus=S.tier-1,en=isEnglishPreview();
  $("attrs").innerHTML=activeAttrs().map(([key,name,desc])=>`<div class="attribute"><span class="score">${attrValue(key)}</span><h3>${name}</h3><p>${desc}</p><div class="attr-controls"><div><span class="control-label">${en?"Base":"База"}</span><div class="attr-base-picker" role="group" aria-label="${en?"Base":"База"}: ${name}">${[2,3,4].map(v=>`<button type="button" class="${S.attrs[key]===v?"on":""}" data-attr-base-btn="${key}" data-value="${v}" aria-pressed="${S.attrs[key]===v}">${v}</button>`).join("")}</div></div><label>${en?"Growth":"Рост"}<select data-attr-bonus="${key}">${Array.from({length:maxBonus+1},(_,v)=>`<option ${S.attrBonus[key]===v?"selected":""}>+${v}</option>`).join("")}</select></label></div></div>`).join("");
  $("tech-conversions").innerHTML=Array.from({length:S.tier},(_,v)=>`<option value="${v}" ${S.techConversions===v?"selected":""}>${v} (${v*2} ${en?"Lv.":"Ур."})</option>`).join("");
  $("conversion-attr").innerHTML=activeAttrs().map(([k,n])=>`<option value="${k}" ${S.conversionAttr===k?"selected":""}>${n}</option>`).join("");
}
function renderOutlooks(){
  $("outlook-description")?.remove();
  const outlooks=activeOutlooks(),en=isEnglishPreview();
  $("outlooks").innerHTML=outlooks.map(o=>{const selected=S.outlooks.includes(o.id),primary=S.primaryOutlook===o.id;return `<button type="button" class="choice ${selected?"selected":""} ${primary?"primary-choice":""}" data-outlook="${o.id}" aria-pressed="${selected}"><strong>${esc(o.name)}</strong><small>${esc(o.category||"")}</small></button>`}).join("");
  const selected=outlooks.filter(o=>S.outlooks.includes(o.id));
  const open=outlooks.find(o=>o.id===S.primaryOutlook)||selected[0];
  $("outlooks").insertAdjacentHTML("afterend",`<div id="outlook-description" class="outlook-description" ${open?"":"hidden"}>${open?`<strong>${esc(open.name)}</strong><p>${md(open.description||open.desc)}</p>${open.bondActions?`<small>${en?"Bond Actions":"Действия Связи"}: ${esc(open.bondActions)}</small>`:""}`:""}</div>`);
  const primary=selected.find(o=>o.id===S.primaryOutlook),builtin=primary?.builtin,builtinGifts=$("builtin-gifts");
  builtinGifts.hidden=!builtin;
  builtinGifts.innerHTML=builtin?`<div class="builtin-gift-heading"><strong>${en?"Inherent Boon":"Обязательный Дар"}</strong><span>${en?"Granted automatically and does not use a slot":"Получен автоматически и не занимает слот"}</span></div><article class="catalog-card gift-card builtin-gift selected"><header><h3>${esc(builtin.name)}</h3><span class="meta">${esc(primary.name)} · ${en?"Primary":"Основное"}</span></header><p>${md(builtin.text)}</p></article>`:"";
  $("gifts").innerHTML=selected.flatMap(o=>o.gifts.map(g=>`<article class="catalog-card gift-card ${S.gifts.includes(g.id)?"selected":""}"><button type="button" data-gift="${g.id}" aria-pressed="${S.gifts.includes(g.id)}"><header><h3>${esc(g.name)}</h3><span class="meta">${esc(o.name)}</span></header><p>${md(g.text)}</p></button></article>`)).join("")||`<p class="autosave">${en?"Choose an Outlook first.":"Сначала выберите Мировоззрение."}</p>`;
}
function selectedBondActions(){return activeOutlooks().filter(outlook=>S.outlooks.includes(outlook.id)&&outlook.bondActions).map(outlook=>`${outlook.name}: ${outlook.bondActions}`).filter(Boolean)}
function renderBondTraining(){
  const root=$("bond-training-content"),chosen=selectedBondActions(),en=isEnglishPreview();
  root.innerHTML=`<div class="builder-bond-summary"><div><small>${en?"Favored Actions":"Избранные действия"}</small><strong>${chosen.length?chosen.map(esc).join("<br>"):(en?"Choose an Outlook first":"Сначала выберите Мировоззрение")}</strong><span>${en?"Bond rules remain on the Russian mechanical layer during this preview.":"Стоимость в 1 Влияние можно заменить 1 Стрессом."}</span></div>${en?"":`<a class="file-button" href="?mode=rules#rules-bonds">Как работают Связи</a>`}</div>`;
}
function wordOptions(group){return `<option value="">${isEnglishPreview()?"Choose a word…":"Выберите слово…"}</option>`+activeAbilityWords()[group].map(w=>`<option value="${w.id}">${esc(w.name)} · ${esc(w.costLabel)}${w.marks?" "+esc(w.marks):""}</option>`).join("")}
function customWordCostOptions(selected=1){return [-1,0,1,2,3,4,"X"].map(value=>`<option value="${value}" ${String(selected)===String(value)?"selected":""}>${value}</option>`).join("")}
const ABILITY_MARK_HELP={"✢":"Способность заканчивается после Существительного и не получает Условие.","✝":"Категорию можно сузить до одной вещи и снизить стоимость на 1.","☾":"Нужно выбрать другое Существительное для X; цена X равна его стоимости."};
function abilityMarkTitle(marks){const en=isEnglishPreview(),help=en?{"✢":"The Ability ends after its Noun and has no Condition.","✝":"Narrow the category to one thing to reduce its cost by 1.","☾":"Choose another Noun for X; X uses that word's cost."}:ABILITY_MARK_HELP;return [...String(marks||"")].map(mark=>`${mark} ${help[mark]||""}`).join(" ")}
function renderAbilityEditor(ability,key,prefix){
  const en=isEnglishPreview(),groups=en?[["verbs","Verbs"],["nouns","Nouns"],["conditions","Conditions"]]:[["verbs","Глаголы"],["nouns","Существительные"],["conditions","Условия"]];
  const selectedWords=group=>ability.words[group].map(id=>{const word=wordById(id,ability);if(!word)return"";const custom=id.startsWith("custom:"),price=custom?`<label class="custom-word-price">${en?"Cost":"Цена"}<select data-ability-key="${key}" data-custom-word-cost="${id}">${customWordCostOptions(word.costLabel)}</select></label>`:"",narrow=word.marks.includes("✝")?`<label class="word-narrow">${en?"One specific thing (−1)":"Только одна вещь (−1)"}<input data-ability-key="${key}" data-word-specialization="${id}" maxlength="120" value="${esc(ability.specializations[id]||"")}" placeholder="${en?"Which one?":"Какая именно?"}"></label>`:"";return `<span class="word-choice"><span class="word" ${word.marks?`title="${esc(abilityMarkTitle(word.marks))}"`:""}>${esc(word.name)} ${word.marks?`<b class="word-marks">${esc(word.marks)}</b>`:""} <small>${esc(word.costLabel)}</small><button type="button" data-ability-key="${key}" data-word-remove="${id}" data-word-group="${group}" aria-label="${en?"Remove":"Убрать"} ${esc(word.name)}">×</button></span>${price}${narrow}</span>`}).join("");
  const customXNouns=ability.words.nouns.map(id=>wordById(id,ability)).filter(word=>word?.id.startsWith("custom:")),xNouns=activeAbilityWords().nouns.concat(customXNouns),variable=abilityNeedsX(ability),xWord=wordById(ability.xNoun,ability);
  const xNarrow=xWord?.marks.includes("✝")?`<label>${en?"Specify X (−1)":"Конкретизация X (−1)"}<input data-ability-key="${key}" data-word-specialization="${xWord.id}" maxlength="120" value="${esc(ability.specializations[xWord.id]||"")}" placeholder="${en?"One thing in the category":"Одна вещь из категории"}"></label>`:"";
  const xPicker=variable?`<label>${en?"Noun for X":"Существительное X"}<select data-ability-key="${key}" data-ability-field="xNoun"><option value="">${en?"Choose X…":"Выберите X…"}</option>${xNouns.map(word=>`<option value="${word.id}" ${ability.xNoun===word.id?"selected":""}>${esc(word.name)} · ${esc(word.costLabel)}</option>`).join("")}</select><small>${en?"The ☾ symbol requires a separate Noun; if a word costs X, use the selected word's cost.":"Метка ☾ требует отдельное Существительное; если цена слова равна X, берётся стоимость выбранного слова."}</small></label>${xNarrow}`:"";
  return `<div class="ability-grid" ${ability.enabled?"":"hidden"}><label>${en?"Name":"Название"}<input data-ability-key="${key}" data-ability-field="name" value="${esc(ability.name)}" placeholder="${en?"Shadow lord":"Повелитель теней"}"></label>${groups.map(([group,label])=>`<div class="word-picker"><label for="${prefix}-word-${group}">${label}</label><div class="word-group"><select id="${prefix}-word-${group}" data-ability-key="${key}" data-word-select="${group}">${wordOptions(group)}</select><button type="button" data-ability-key="${key}" data-word-add="${group}">${en?"Add selected":"Добавить выбранное"}</button></div><div class="custom-word"><input id="${prefix}-custom-${group}" maxlength="80" placeholder="${en?"Custom word":"Своё слово"}"><label>${en?"Cost":"Цена"}<select id="${prefix}-custom-cost-${group}">${customWordCostOptions(1)}</select></label><button type="button" data-ability-key="${key}" data-custom-word-add="${group}">${en?"Add custom":"Добавить своё"}</button></div><small>${en?"Set a Narrator-approved cost from -1 to 4, or X.":"Для собственного слова укажите согласованную с Нарратором цену от −1 до 4 или X."}</small><div class="selected-words">${selectedWords(group)}</div></div>`).join("")}<div class="field-grid three"><label>${en?"Rank":"Ранг"}<select data-ability-key="${key}" data-ability-field="rank">${[1,2,3].map(value=>`<option ${ability.rank===value?"selected":""}>${value}</option>`).join("")}</select></label>${xPicker}<label>${en?"Total cost":"Итоговая цена"}<input value="${abilityCost(ability)}" disabled></label></div>${variable&&xWord?`<div class="formula">X = “${esc(xWord.name)}”, cost ${xWord.costLabel}.</div>`:""}<label>${en?"Notes":"Пояснение"}<textarea data-ability-key="${key}" data-ability-field="desc" rows="3" placeholder="${en?"Ability limits and aesthetics":"Границы и эстетика Способности"}">${esc(ability.desc)}</textarea></label><div class="formula">${abilityFormula(ability)}</div></div>`;
}
function renderSkillsAbility(){
  const en=isEnglishPreview();
  $("skills").innerHTML=S.skills.map(s=>{const performance=hasGift("Performance Artist")&&S.mods.performanceSkill===s.id;return `<div class="skill-row"><label>${en?"Skill":"Навык"}<input data-skill-name="${s.id}" value="${esc(s.name)}" placeholder="${en?"Rooftop parkour":"Паркур по крышам"}"></label><label>${performance?(en?"Bought / total":"Куплено / итог"):(en?"Rank":"Ранг")}<select class="rank-select" data-skill-rank="${s.id}">${[1,2,3].map(v=>`<option ${s.rank===v?"selected":""}>${performance?`${v} / ${Math.min(3,v+1)}`:v}</option>`).join("")}</select></label><button type="button" class="remove" data-skill-remove="${s.id}" aria-label="${en?"Remove Skill":"Удалить Навык"}">×</button></div>`}).join("");
  $("ability-enabled").checked=S.ability.enabled;
  $("ability-builder").innerHTML=renderAbilityEditor(S.ability,"ability","ability");
  const b=budgets(),rankSources=[];
  if(b.unrestrictedExtra)rankSources.push(`«Глухота к сверхъестественному»: +${b.unrestrictedExtra} свободных`);
  if(b.darkUrgeRanks)rankSources.push(`«Темный порыв»: +${b.darkUrgeRanks} только на Способность`);
  if(b.uncontrollableRanks)rankSources.push(`«Неконтролируемая сила»: +${b.uncontrollableRanks} только на Способность`);
  $("rank-modifiers").innerHTML=`<p>Всего доступно Рангов: <strong>${b.rankPool}</strong>. Основной бюджет: ${b.coreRankSpent} из ${b.coreRankPool}${b.unrestrictedExtra?` (${b.rankBase} базовых + ${b.unrestrictedExtra} свободных от Дара)`:""}.</p>${rankSources.length?`<ul>${rankSources.map(source=>`<li>${source}</li>`).join("")}</ul>`:"<p>Дополнительных Рангов от Даров нет.</p>"}${b.abilityExtra?`<p>Резерв текущей Способности: <strong>${b.abilityExtra}</strong>; использовано ${b.abilityExtraUsed}, осталось ${b.abilityExtraRemaining}; стоимость ${b.aCost}, из основного бюджета оплачивается ${b.paidAbility}.</p>`:""}${hasGift("Performance Artist")?`<label>Дополнительный Ранг «Артиста»<select id="performance-skill"><option value="">Выберите Навык…</option>${S.skills.map(skill=>`<option value="${skill.id}" ${S.mods.performanceSkill===skill.id?"selected":""}>${esc(skill.name||"Без названия")} · куплено ${skill.rank}, итог ${Math.min(3,skill.rank+1)}</option>`).join("")}</select></label><small>Дар повышает итоговый Ранг выбранного Навыка на 1, но не выше 3; этот Ранг не расходует основной бюджет.</small>`:""}${b.gadgetPool?`<br><label>Гаджеты «Технаря» — суммарная стоимость в Рангах <input id="gadget-spent" type="number" min="0" max="99" value="${b.gadgetSpent}"></label><small>Первые ${b.gadgetPool} Ранга оплачивает Дар; ещё ${b.paidGadgets} расходуется из основного бюджета.</small>`:""}${hasGift("Tainted Body")?`<br><label class="switch"><input id="tainted-toggle" type="checkbox" ${S.mods.taintedBody?"checked":""}><span>«Порченое тело» уже раскрыто в этой Серии</span></label><small>Один раз за Серию, когда вы тратите Влияние, Дар даёт ${3+S.tier} Рангов только для получения и/или повышения Ранга новой отдельной Способности.</small>${S.mods.taintedBody?`<p>Новая Способность: использовано <strong>${b.taintedAbilitySpent}</strong> из <strong>${b.taintedAbilityPool}</strong>, осталось ${b.taintedAbilityRemaining}${b.taintedAbilityOver?`; перерасход ${b.taintedAbilityOver}`:""}.</p>`:""}`:""}`;
  if(en)$("rank-modifiers").innerHTML=`<p>Total available Ranks: <strong>${b.rankPool}</strong>. Core budget: ${b.coreRankSpent} of ${b.coreRankPool}.</p>${b.abilityExtra?`<p>Ability reserve: <strong>${b.abilityExtra}</strong>; ${b.abilityExtraUsed} used, ${b.abilityExtraRemaining} remaining.</p>`:"<p>No additional Ranks from Boons.</p>"}${hasGift("Tainted Body")?`<br><label class="switch"><input id="tainted-toggle" type="checkbox" ${S.mods.taintedBody?"checked":""}><span>Tainted Body has manifested this Series</span></label><small>Its separate Ability uses a special reserve of ${3+S.tier} Ranks.</small>`:""}`;
  const taintedSection=$("tainted-ability-section");taintedSection.hidden=!(hasGift("Tainted Body")&&S.mods.taintedBody);if(!taintedSection.hidden)$("tainted-ability-builder").innerHTML=renderAbilityEditor(S.taintedAbility,"taintedAbility","tainted");
}
function abilityFormula(ability=S.ability){const en=isEnglishPreview();if(!ability.enabled)return en?"No Ability selected.":"Способность не выбрана.";const first=group=>(wordById(ability.words[group][0],ability)?.name||`[${en?(group==="verbs"?"Verb":group==="nouns"?"Noun":"Condition"):(group==="verbs"?"Глагол":group==="nouns"?"Существительное":"Условие")}]`);const uncontrollable=ability===S.ability&&hasGift("Uncontrollable Power"),noCondition=!uncontrollable&&ability.words.verbs.concat(ability.words.nouns).some(id=>wordById(id,ability)?.marks.includes("✢"));const x=wordById(ability.xNoun,ability)?.name||"X",verb=first("verbs").replaceAll("X",x),noun=first("nouns").replaceAll("X",x),condition=first("conditions").replaceAll("X",x);if(en)return `You can ${verb.toLowerCase()} ${noun.toLowerCase()}${noCondition?".":`, so long as ${condition.toLowerCase()}.`}`;return `${uncontrollable?"Вы":"Вы можете"} ${verb.toLowerCase()} ${noun.toLowerCase()}${noCondition?".":uncontrollable?`, когда ${condition.toLowerCase()}.`:` пока ${condition.toLowerCase()}.`}`;}

function renderTechniques(){
  const archetypes=activeArchetypes(),en=isEnglishPreview();
  $("arch-tabs").innerHTML=archetypes.map(a=>`<button type="button" class="${activeArch===a.id?"on":""}" data-arch="${a.id}">${esc(a.name)}</button>`).join("");
  const arch=archetypes.find(a=>a.id===activeArch)||archetypes[0],q=$("tech-search").value.trim().toLowerCase(),tagList=t=>String(t.tags||"").split(",").map(tag=>tag.trim()).filter(Boolean),tags=[...new Set(arch.techniques.flatMap(tagList))].sort((a,b)=>a.localeCompare(b,en?"en":"ru"));
  if(techTag!=="all"&&!tags.includes(techTag))techTag="all";
  $("tech-tag-filters").innerHTML=`<label class="tag-picker"><span>${en?"Tag":"Тег"}</span><select data-tech-tag-select>${["all",...tags].map(tag=>`<option value="${esc(tag)}" ${techTag===tag?"selected":""}>${tag==="all"?(en?"All tags":"Все теги"):esc(tag)}</option>`).join("")}</select></label>`;
  $("tech-sort").value=techSort;
  const list=arch.techniques.filter(t=>(techTag==="all"||tagList(t).includes(techTag))&&(!q||`${t.name} ${t.en||""} ${t.tags} ${t.flavor} ${t.levels.map(l=>l.text).join(" ")}`.toLowerCase().includes(q))).map((technique,index)=>({technique,index}));
  if(techSort==="name")list.sort((a,b)=>a.technique.name.localeCompare(b.technique.name,en?"en":"ru"));
  if(techSort==="stars")list.sort((a,b)=>a.technique.stars-b.technique.stars||a.technique.name.localeCompare(b.technique.name,en?"en":"ru"));
  $("tech-list").innerHTML=list.map(({technique:t})=>{const level=S.techniques[t.id]||0,learned=!en&&t.id==="ruiner.spellcrafter"?[...new Set(S.mods.spellcrafterAugments||[])]:[],spellLimit=level>=3?2:level>=1?1:0,names={fierce:"Свирепая",focused:"Сфокусированная",wild:"Дикая",outstanding:"Выдающаяся"},spellPicker=!en&&t.id==="ruiner.spellcrafter"&&level?`<fieldset class="modifier-choice-grid"><legend>Изученные Модификации · ${learned.length}/${spellLimit}</legend>${Object.entries(names).map(([id,name])=>`<button type="button" class="${learned.includes(id)?"on":""}" data-spellcrafter-learn="${id}">${name}</button>`).join("")}</fieldset>`:"",wispNames={dreamy:"Мечтательный",angry:"Злой",insightful:"Проницательный",bright:"Пылкий",kind:"Добрый",fierce:"Яростный"},wispLearned=!en&&t.id==="altruist.will-o-wisp"?[...new Set(S.mods.wispSpiritTypes||[])]:[],wispLimit=level>=3?2:level>=1?1:0,wispPicker=!en&&t.id==="altruist.will-o-wisp"&&level?`<fieldset class="modifier-choice-grid"><legend>Известные Духи · ${wispLearned.length}/${wispLimit}</legend>${Object.entries(wispNames).map(([id,name])=>`<button type="button" class="${wispLearned.includes(id)?"on":""}" data-wisp-learn="${id}">${name}</button>`).join("")}</fieldset>`:"";return `<article class="catalog-card ${level?"selected":""}"><header><div><h3>${esc(t.name)} <small>${"★".repeat(t.stars)}</small></h3><div class="meta">${esc(t.tags)}</div></div><div class="pips"><button type="button" class="pip ${level>=1?"on":""}" data-tech="${t.id}" data-level="1">1</button><button type="button" class="pip ${level>=2?"on":""}" data-tech="${t.id}" data-level="2">2</button><button type="button" class="pip ${level>=3?"on":""}" data-tech="${t.id}" data-level="3">3</button></div></header><p>${md(t.flavor)}</p><div class="tech-levels">${t.levels.map(l=>`<div class="tech-level ${level<l.n?"locked":""}"><strong>${en?"":automationBadge(techniqueLevelAutomation(t.id,l.n))}${l.n}: ${esc(l.name)}</strong><br>${md(l.text)}</div>`).join("")}</div>${spellPicker}${wispPicker}</article>`}).join("")||`<p>${en?"Nothing found.":"Ничего не найдено."}</p>`;
}
function selectedOutlookGifts(){return activeOutlooks().filter(o=>S.outlooks.includes(o.id)).map(o=>({outlook:o,gifts:(o.builtin&&o.id===S.primaryOutlook?[o.builtin]:[]).concat(o.gifts.filter(g=>S.gifts.includes(g.id)))}));}
function renderSheet(){
  const d=derived(),en=isEnglishPreview(),attrs=en?activeAttrs():ATTRS,activeTechniqueIds=new Set(activeArchetypes().flatMap(archetype=>archetype.techniques.map(technique=>technique.id))); const techs=Object.entries(S.techniques).filter(([id,v])=>v>0&&activeTechniqueIds.has(id)).map(([id,level])=>({tech:techById(id),level})).filter(x=>x.tech);
  const words=en?{unnamed:"Unnamed hero",concept:"No concept recorded",player:"player",tier:"Tier",stats:[["Health",d.hp],["Guts",d.guts],["Speed",d.speed],["Focus",d.focus]],attrs:"Attributes",outlooks:"Outlooks and Boons",primary:"Primary",skills:"Skills",artist:"Performance Artist",ability:"Ability",rank:"Rank",roll:"Add to roll",tainted:"New Tainted Body Ability",bonds:"Bonds",quick:"Quick",noTags:"No tags",techniques:"Techniques",level:"Level"}:{unnamed:"Безымянный герой",concept:"Концепция не записана",player:"игрок",tier:"Ступень",stats:[["Здоровье",d.hp],["Стойкость",d.guts],["Скорость",d.speed],["Фокус",d.focus]],attrs:"Атрибуты",outlooks:"Мировоззрения и Дары",primary:"Основное",skills:"Навыки",artist:"Артист",ability:"Способность",rank:"Ранг",roll:"Добавить в бросок",tainted:"Новая Способность «Порченого тела»",bonds:"Связи",quick:"Быстрая",noTags:"Без тегов",techniques:"Техники",level:"Уровень"};
  $("sheet").innerHTML=`<header>${S.media.portrait?`<img class="sheet-portrait" src="${S.media.portrait}" alt="">`:""}<div><h2>${esc(S.name||words.unnamed)}</h2><div class="sheet-sub">${esc(S.concept||words.concept)}${S.player?` · ${words.player}: ${esc(S.player)}`:""} · ${words.tier} ${S.tier}</div></div></header><div class="sheet-stats">${words.stats.map(([n,v])=>`<div class="sheet-stat"><span>${n}</span><strong>${v}</strong></div>`).join("")}</div><div class="sheet-columns"><section class="sheet-block"><h3>${words.attrs}</h3><div class="sheet-roll-list">${attrs.map(([k,n])=>`<button type="button" data-sheet-tool-attr="${k}"><span>${n}</span><strong>${attrValue(k)}D6</strong></button>`).join("")}</div></section><section class="sheet-block"><h3>${words.outlooks}</h3>${selectedOutlookGifts().map(({outlook,gifts})=>`<h4>${esc(outlook.name)}${outlook.id===S.primaryOutlook?` · ${words.primary}`:""}</h4><ul>${gifts.map(g=>`<li><strong>${esc(g.name)}</strong> — ${md(g.text)}</li>`).join("")||"<li>—</li>"}</ul>`).join("")||"<p>—</p>"}</section><section class="sheet-block"><h3>${words.skills}</h3><div class="sheet-roll-list">${S.skills.filter(s=>s.name.trim()).map(s=>`<button type="button" data-sheet-tool-skill="${s.id}"><span>${esc(s.name)}${hasGift("Performance Artist")&&S.mods.performanceSkill===s.id?` · ${words.artist}`:""}</span><strong>+${effectiveSkillRank(s)}D6</strong></button>`).join("")||"<p>—</p>"}</div>${S.ability.enabled?`<h3>${words.ability} · ${words.rank} ${S.ability.rank}</h3><p><strong>${esc(S.ability.name||abilityFormula())}</strong><br>${esc(abilityFormula())}<br>${md(S.ability.desc)}</p><button type="button" class="sheet-roll-action" data-sheet-tool-ability="main">${words.roll} · +${S.ability.rank}D6</button>`:""}${S.mods.taintedBody&&S.taintedAbility.enabled?`<h3>${words.tainted} · ${words.rank} ${S.taintedAbility.rank}</h3><p><strong>${esc(S.taintedAbility.name||abilityFormula(S.taintedAbility))}</strong><br>${esc(abilityFormula(S.taintedAbility))}<br>${md(S.taintedAbility.desc)}</p><button type="button" class="sheet-roll-action" data-sheet-tool-ability="tainted">${words.roll} · +${S.taintedAbility.rank}D6</button>`:""}</section><section class="sheet-block"><h3>${words.bonds}</h3>${S.bonds.map(bond=>`<p><strong>${esc(bond.name)} · ${words.rank} ${bond.rank}</strong>${bond.quick?` · ${words.quick}`:""}<br>${bond.tags.length?bond.tags.map(esc).join(" · "):words.noTags}</p>`).join("")||"<p>—</p>"}</section><section class="sheet-block"><h3>${words.techniques}</h3>${techs.map(({tech,level})=>`<h4>${esc(tech.name)} · ${words.level} ${level}</h4>${tech.levels.slice(0,level).map(l=>`<p><strong>${en?"":automationBadge(techniqueLevelAutomation(tech.id,l.n))}${l.n}: ${esc(l.name)}</strong> — ${md(l.text)}</p>`).join("")}`).join("")||"<p>—</p>"}</section></div>`;
}

function counter(key,label,value,max=null){return `<article class="counter"><header><span>${label}</span><span>${max===null?"":`макс. ${max}`}</span></header><input type="number" data-counter-input="${key}" value="${value}" min="0" ${max!==null?`max="${max}"`:""}><div class="counter-controls"><button type="button" data-counter="${key}" data-delta="-1">−</button><button type="button" data-counter="${key}" data-delta="1">+</button></div></article>`}
