"use strict";

function renderSidebar(){
  const d=derived(),b=budgets(); ensureRuntime();
  $("derived").innerHTML=[[t("builder.stat.health"),d.hp],...(d.guts==null?[]:[[t("builder.stat.guts"),d.guts]]),[t("builder.stat.speed"),d.speed],[t("builder.stat.focus"),d.focus]].map(([n,v])=>`<div class="derived"><span>${n}</span><strong>${v}</strong></div>`).join("");
  $("budgets").innerHTML=budgetRow(t("builder.budget.attributes"),b.attrSpent,b.attrPool)+budgetRow(t("builder.budget.boons"),b.giftSpent,b.giftPool)+budgetRow(t("builder.budget.ranks"),b.rankSpent,b.rankPool,Boolean(b.rankOver||b.taintedAbilityOver||b.rankBudgetConflict))+budgetRow(t("builder.budget.techniques"),b.techSpent,b.techPool);
  const list=issues();
  const completed=[S.name.trim(),Object.values(S.attrs).sort().join(",")==="2,2,3,4",S.primaryOutlook,b.giftSpent===b.giftPool,b.skillSpent>=b.skillMin,b.rankOver===0&&!b.taintedAbilityOver&&!b.rankBudgetConflict,b.techSpent===b.techPool].filter(Boolean).length;
  $("warnings").innerHTML=list.map(([kind,text])=>`<div class="warning ${kind}">${esc(text)}</div>`).join("")||`<div class="warning" style="border-color:var(--good)">${t("builder.status.valid")}</div>`;
  $("build-progress").textContent=t("builder.progress",{completed,status:t(list.some(i=>i[0]==="bad")?"builder.progress.review":"builder.progress.valid")});
}
function renderHeroSelect(){
  $("hero-select").innerHTML=store.heroes.map((h,i)=>({h,i})).filter(({h})=>(h.rulesEdition||"ru-v0.9")===contentPreferences.edition).map(({h,i})=>`<option value="${i}" ${i===store.current?"selected":""}>${esc(h.name||t("builder.hero.unnamed"))} · ${t("builder.hero.tierShort")}${h.tier}</option>`).join("");
  if($("scene-hero-select")){const previous=$("scene-hero-select").value,editionHeroes=store.heroes.filter(h=>(h.rulesEdition||"ru-v0.9")===contentPreferences.edition);$("scene-hero-select").innerHTML=editionHeroes.map(h=>`<option value="${h.id}">${esc(h.name||t("builder.hero.unnamed"))} · ${t("builder.hero.tierShort")}${h.tier}</option>`).join("");$("scene-hero-select").value=editionHeroes.some(h=>h.id===previous)?previous:S.id}
}
function renderProfile(){const hero=S.name||t("builder.hero.unnamed");for(const key of ["name","player","concept"])$("f-"+key).value=S[key];$("f-tier").value=S.tier;$("hero-portrait-preview").innerHTML=S.media.portrait?`<img src="${S.media.portrait}" alt="${esc(t("builder.media.portraitOf",{hero}))}">`:`<span>${t("builder.media.portrait")}</span>`;$("hero-token-preview").innerHTML=S.media.token?`<img src="${S.media.token}" alt="${esc(t("builder.media.tokenOf",{hero}))}">`:`<span>${t("builder.media.token")}</span>`;$("hero-portrait-clear").disabled=!S.media.portrait;$("hero-token-clear").disabled=!S.media.token}
function renderAttrs(){
  const maxBonus=S.tier-1;
  $("attrs").innerHTML=activeAttrs().map(([key,name,desc])=>`<div class="attribute"><span class="score">${attrValue(key)}</span><h3>${name}</h3><p>${desc}</p><div class="attr-controls"><div><span class="control-label">${t("builder.attributes.base")}</span><div class="attr-base-picker" role="group" aria-label="${t("builder.attributes.base")}: ${name}">${[2,3,4].map(v=>`<button type="button" class="${S.attrs[key]===v?"on":""}" data-attr-base-btn="${key}" data-value="${v}" aria-pressed="${S.attrs[key]===v}">${v}</button>`).join("")}</div></div><label>${t("builder.attributes.growth")}<select data-attr-bonus="${key}">${Array.from({length:maxBonus+1},(_,v)=>`<option ${S.attrBonus[key]===v?"selected":""}>+${v}</option>`).join("")}</select></label></div></div>`).join("");
  $("tech-conversions").innerHTML=Array.from({length:S.tier},(_,v)=>`<option value="${v}" ${S.techConversions===v?"selected":""}>${v} (${v*2} ${t("builder.attributes.levelShort")})</option>`).join("");
  $("conversion-attr").innerHTML=activeAttrs().map(([k,n])=>`<option value="${k}" ${S.conversionAttr===k?"selected":""}>${n}</option>`).join("");
}
function renderOutlooks(){
  $("outlook-description")?.remove();
  const outlooks=activeOutlooks();
  $("outlooks").innerHTML=outlooks.map(o=>{const selected=S.outlooks.includes(o.id),primary=S.primaryOutlook===o.id;return `<button type="button" class="choice ${selected?"selected":""} ${primary?"primary-choice":""}" data-outlook="${o.id}" aria-pressed="${selected}"><strong>${esc(o.name)}</strong><small>${esc(o.category||"")}</small></button>`}).join("");
  const selected=outlooks.filter(o=>S.outlooks.includes(o.id));
  const open=outlooks.find(o=>o.id===S.primaryOutlook)||selected[0];
  $("outlooks").insertAdjacentHTML("afterend",`<div id="outlook-description" class="outlook-description" ${open?"":"hidden"}>${open?`<strong>${esc(open.name)}</strong><p>${md(open.description||open.desc)}</p>${open.bondActions?`<small>${t("builder.outlooks.bondActions")}: ${esc(open.bondActions)}</small>`:""}`:""}</div>`);
  const primary=selected.find(o=>o.id===S.primaryOutlook),builtin=primary?.builtin,builtinGifts=$("builtin-gifts");
  builtinGifts.hidden=!builtin;
  builtinGifts.innerHTML=builtin?`<div class="builtin-gift-heading"><strong>${t("builder.outlooks.inherent")}</strong><span>${t("builder.outlooks.inherentHelp")}</span></div><article class="catalog-card gift-card builtin-gift selected"><header><h3>${esc(builtin.name)}</h3><span class="meta">${esc(primary.name)} · ${t("builder.outlooks.primary")}</span></header><p>${md(builtin.text)}</p></article>`:"";
  $("gifts").innerHTML=selected.flatMap(o=>o.gifts.map(g=>`<article class="catalog-card gift-card ${S.gifts.includes(g.id)?"selected":""}"><button type="button" data-gift="${g.id}" aria-pressed="${S.gifts.includes(g.id)}"><header><h3>${esc(g.name)}</h3><span class="meta">${esc(o.name)}</span></header><p>${md(g.text)}</p></button></article>`)).join("")||`<p class="autosave">${t("builder.outlooks.choose")}</p>`;
}
function selectedBondActions(){return activeOutlooks().filter(outlook=>S.outlooks.includes(outlook.id)&&outlook.bondActions).map(outlook=>`${outlook.name}: ${outlook.bondActions}`).filter(Boolean)}
function renderBondTraining(){
  const root=$("bond-training-content"),chosen=selectedBondActions();
  root.innerHTML=`<div class="builder-bond-summary"><div><small>${t("builder.bonds.favored")}</small><strong>${chosen.length?chosen.map(esc).join("<br>"):t("builder.bonds.choose")}</strong><span>${t(isLionwingEdition()?"builder.bonds.lionwingHelp":"builder.bonds.legacyHelp")}</span></div>${isLionwingEdition()?"":`<a class="file-button" href="?mode=rules#rules-bonds">${t("builder.bonds.rulesLink")}</a>`}</div>`;
}
function wordOptions(group){return `<option value="">${t("builder.ability.chooseWord")}</option>`+activeAbilityWords()[group].map(w=>`<option value="${w.id}">${esc(w.name)} · ${esc(w.costLabel)}${w.marks?" "+esc(w.marks):""}</option>`).join("")}
function customWordCostOptions(selected=1){return [-1,0,1,2,3,4,"X"].map(value=>`<option value="${value}" ${String(selected)===String(value)?"selected":""}>${value}</option>`).join("")}
function abilityMarkTitle(marks){const help={"✢":t("builder.ability.markStop"),"✝":t("builder.ability.markNarrow"),"☾":t("builder.ability.markX")};return [...String(marks||"")].map(mark=>`${mark} ${help[mark]||""}`).join(" ")}
function renderAbilityEditor(ability,key,prefix){
  const groups=[["verbs",t("builder.ability.group.verbs")],["nouns",t("builder.ability.group.nouns")],["conditions",t("builder.ability.group.conditions")]];
  const selectedWords=group=>ability.words[group].map(id=>{const word=wordById(id,ability);if(!word)return"";const custom=id.startsWith("custom:"),price=custom?`<label class="custom-word-price">${t("builder.ability.cost")}<select data-ability-key="${key}" data-custom-word-cost="${id}">${customWordCostOptions(word.costLabel)}</select></label>`:"",narrow=word.marks.includes("✝")?`<label class="word-narrow">${t("builder.ability.oneThing")}<input data-ability-key="${key}" data-word-specialization="${id}" maxlength="120" value="${esc(ability.specializations[id]||"")}" placeholder="${t("builder.ability.whichOne")}"></label>`:"";return `<span class="word-choice"><span class="word" ${word.marks?`title="${esc(abilityMarkTitle(word.marks))}"`:""}>${esc(word.name)} ${word.marks?`<b class="word-marks">${esc(word.marks)}</b>`:""} <small>${esc(word.costLabel)}</small><button type="button" data-ability-key="${key}" data-word-remove="${id}" data-word-group="${group}" aria-label="${t("builder.action.remove")} ${esc(word.name)}">×</button></span>${price}${narrow}</span>`}).join("");
  const customXNouns=ability.words.nouns.map(id=>wordById(id,ability)).filter(word=>word?.id.startsWith("custom:")),xNouns=activeAbilityWords().nouns.concat(customXNouns),variable=abilityNeedsX(ability),xWord=wordById(ability.xNoun,ability);
  const xNarrow=xWord?.marks.includes("✝")?`<label>${t("builder.ability.specifyX")}<input data-ability-key="${key}" data-word-specialization="${xWord.id}" maxlength="120" value="${esc(ability.specializations[xWord.id]||"")}" placeholder="${t("builder.ability.oneThingCategory")}"></label>`:"";
  const xPicker=variable?`<label>${t("builder.ability.nounForX")}<select data-ability-key="${key}" data-ability-field="xNoun"><option value="">${t("builder.ability.chooseX")}</option>${xNouns.map(word=>`<option value="${word.id}" ${ability.xNoun===word.id?"selected":""}>${esc(word.name)} · ${esc(word.costLabel)}</option>`).join("")}</select><small>${t("builder.ability.xHelp")}</small></label>${xNarrow}`:"";
  return `<div class="ability-grid" ${ability.enabled?"":"hidden"}><label>${t("builder.ability.name")}<input data-ability-key="${key}" data-ability-field="name" value="${esc(ability.name)}" placeholder="${t("builder.ability.namePlaceholder")}"></label>${groups.map(([group,label])=>`<div class="word-picker"><label for="${prefix}-word-${group}">${label}</label><div class="word-group"><select id="${prefix}-word-${group}" data-ability-key="${key}" data-word-select="${group}">${wordOptions(group)}</select><button type="button" data-ability-key="${key}" data-word-add="${group}">${t("builder.ability.addSelected")}</button></div><div class="custom-word"><input id="${prefix}-custom-${group}" maxlength="80" placeholder="${t("builder.ability.customWord")}"><label>${t("builder.ability.cost")}<select id="${prefix}-custom-cost-${group}">${customWordCostOptions(1)}</select></label><button type="button" data-ability-key="${key}" data-custom-word-add="${group}">${t("builder.ability.addCustom")}</button></div><small>${t("builder.ability.customHelp")}</small><div class="selected-words">${selectedWords(group)}</div></div>`).join("")}<div class="field-grid three"><label>${t("builder.ability.rank")}<select data-ability-key="${key}" data-ability-field="rank">${[1,2,3].map(value=>`<option ${ability.rank===value?"selected":""}>${value}</option>`).join("")}</select></label>${xPicker}<label>${t("builder.ability.totalCost")}<input value="${abilityCost(ability)}" disabled></label></div>${variable&&xWord?`<div class="formula">${t("builder.ability.xFormula",{word:esc(xWord.name),cost:xWord.costLabel})}</div>`:""}<label>${t("builder.ability.notes")}<textarea data-ability-key="${key}" data-ability-field="desc" rows="3" placeholder="${t("builder.ability.notesPlaceholder")}">${esc(ability.desc)}</textarea></label><div class="formula">${abilityFormula(ability)}</div></div>`;
}
function renderSkillsAbility(){
  const canonical=activeCanonicalSkills(),suggestions=canonical.length?`<datalist id="canonical-skills">${canonical.map(skill=>`<option value="${esc(skill.name)}">${esc(skill.attribute)}</option>`).join("")}</datalist>`:"";
  $("skills").innerHTML=suggestions+S.skills.map(s=>{const performance=hasGift("Performance Artist")&&S.mods.performanceSkill===s.id;return `<div class="skill-row"><label>${t("builder.skills.skill")}<input data-skill-name="${s.id}" value="${esc(skillDisplayName(s))}" ${canonical.length?'list="canonical-skills"':""} placeholder="${t("builder.skills.placeholder")}"></label><label>${t(performance?"builder.skills.boughtTotal":"builder.skills.rank")}<select class="rank-select" data-skill-rank="${s.id}">${[1,2,3].map(v=>`<option ${s.rank===v?"selected":""}>${performance?`${v} / ${Math.min(3,v+1)}`:v}</option>`).join("")}</select></label><button type="button" class="remove" data-skill-remove="${s.id}" aria-label="${t("builder.skills.remove")}">×</button></div>`}).join("");
  $("ability-enabled").checked=S.ability.enabled;
  $("ability-builder").innerHTML=renderAbilityEditor(S.ability,"ability","ability");
  const b=budgets(),rankSources=[];
  if(b.unrestrictedExtra)rankSources.push(t("builder.ranks.performanceSource",{count:b.unrestrictedExtra}));
  if(b.darkUrgeRanks)rankSources.push(t("builder.ranks.darkUrgeSource",{count:b.darkUrgeRanks}));
  if(b.uncontrollableRanks)rankSources.push(t("builder.ranks.uncontrollableSource",{count:b.uncontrollableRanks}));
  const totalKey=b.unrestrictedExtra?"builder.ranks.totalWithExtra":"builder.ranks.total",total=t(totalKey,{total:`<strong>${b.rankPool}</strong>`,spent:b.coreRankSpent,pool:b.coreRankPool,base:b.rankBase,extra:b.unrestrictedExtra});
  const reserve=b.abilityExtra?`<p>${t("builder.ranks.abilityReserve",{reserve:`<strong>${b.abilityExtra}</strong>`,used:b.abilityExtraUsed,remaining:b.abilityExtraRemaining,cost:b.aCost,paid:b.paidAbility})}</p>`:"";
  const performance=hasGift("Performance Artist")?`<label>${t("builder.ranks.performance")}<select id="performance-skill"><option value="">${t("builder.ranks.chooseSkill")}</option>${S.skills.map(skill=>`<option value="${skill.id}" ${S.mods.performanceSkill===skill.id?"selected":""}>${t("builder.ranks.skillOption",{name:esc(skillDisplayName(skill)||t("builder.ranks.unnamedSkill")),bought:skill.rank,total:Math.min(3,skill.rank+1)})}</option>`).join("")}</select></label><small>${t("builder.ranks.performanceHelp")}</small>`:"";
  const gadgets=b.gadgetPool?`<br><label>${t("builder.ranks.gadgets")} <input id="gadget-spent" type="number" min="0" max="99" value="${b.gadgetSpent}"></label><small>${t("builder.ranks.gadgetsHelp",{pool:b.gadgetPool,paid:b.paidGadgets})}</small>`:"";
  const taintedPool=3+S.tier,over=b.taintedAbilityOver?t("builder.ranks.over",{over:b.taintedAbilityOver}):"",tainted=hasGift("Tainted Body")?`<br><label class="switch"><input id="tainted-toggle" type="checkbox" ${S.mods.taintedBody?"checked":""}><span>${t("builder.ranks.taintedToggle")}</span></label><small>${t("builder.ranks.taintedHelp",{pool:taintedPool})}</small>${S.mods.taintedBody?`<p>${t("builder.ranks.taintedSummary",{spent:`<strong>${b.taintedAbilitySpent}</strong>`,pool:`<strong>${b.taintedAbilityPool}</strong>`,remaining:b.taintedAbilityRemaining,over})}</p>`:""}`:"";
  $("rank-modifiers").innerHTML=`<p>${total}</p>${rankSources.length?`<ul>${rankSources.map(source=>`<li>${source}</li>`).join("")}</ul>`:`<p>${t("builder.ranks.noExtra")}</p>`}${reserve}${performance}${gadgets}${tainted}`;
  const taintedSection=$("tainted-ability-section");taintedSection.hidden=!(hasGift("Tainted Body")&&S.mods.taintedBody);if(!taintedSection.hidden)$("tainted-ability-builder").innerHTML=renderAbilityEditor(S.taintedAbility,"taintedAbility","tainted");
}
function abilityFormula(ability=S.ability){if(!ability.enabled)return t("builder.ability.none");const first=group=>(wordById(ability.words[group][0],ability)?.name||`[${t(`builder.ability.placeholder.${group==="verbs"?"verb":group==="nouns"?"noun":"condition"}`)}]`);const uncontrollable=ability===S.ability&&hasGift("Uncontrollable Power"),noCondition=!uncontrollable&&ability.words.verbs.concat(ability.words.nouns).some(id=>wordById(id,ability)?.marks.includes("✢"));const x=wordById(ability.xNoun,ability)?.name||"X",params={verb:first("verbs").replaceAll("X",x).toLowerCase(),noun:first("nouns").replaceAll("X",x).toLowerCase(),condition:first("conditions").replaceAll("X",x).toLowerCase()};return t(noCondition?"builder.ability.formulaNoCondition":uncontrollable?"builder.ability.formulaUncontrollable":"builder.ability.formula",params);}

function renderTechniques(){
  const archetypes=activeArchetypes(),en=isEnglishPreview();
  const tr=(key,params)=>t(key,params);
  $("arch-tabs").innerHTML=archetypes.map(a=>`<button type="button" class="${activeArch===a.id?"on":""}" data-arch="${a.id}">${esc(a.name)}</button>`).join("");
  const arch=archetypes.find(a=>a.id===activeArch)||archetypes[0],q=$("tech-search").value.trim().toLowerCase(),tagList=t=>String(t.tags||"").split(",").map(tag=>tag.trim()).filter(Boolean),tags=[...new Set(arch.techniques.flatMap(tagList))].sort((a,b)=>a.localeCompare(b,en?"en":"ru"));
  if(techTag!=="all"&&!tags.includes(techTag))techTag="all";
  $("tech-tag-filters").innerHTML=`<label class="tag-picker"><span>${t("builder.catalog.tag")}</span><select data-tech-tag-select>${["all",...tags].map(tag=>`<option value="${esc(tag)}" ${techTag===tag?"selected":""}>${tag==="all"?t("builder.catalog.allTags"):esc(tag)}</option>`).join("")}</select></label>`;
  $("tech-sort").value=techSort;
  const list=arch.techniques.filter(t=>(techTag==="all"||tagList(t).includes(techTag))&&(!q||`${t.name} ${t.en||""} ${t.tags} ${t.flavor} ${t.levels.map(l=>l.text).join(" ")}`.toLowerCase().includes(q))).map((technique,index)=>({technique,index}));
  if(techSort==="name")list.sort((a,b)=>a.technique.name.localeCompare(b.technique.name,en?"en":"ru"));
  if(techSort==="stars")list.sort((a,b)=>a.technique.stars-b.technique.stars||a.technique.name.localeCompare(b.technique.name,en?"en":"ru"));
  $("tech-list").innerHTML=list.map(({technique:t})=>{const level=S.techniques[t.id]||0,learned=t.id==="ruiner.spellcrafter"?[...new Set(S.mods.spellcrafterAugments||[])]:[],spellLimit=level>=3?2:level>=1?1:0,modifierIds=["fierce","focused","wild","outstanding"],spellPicker=t.id==="ruiner.spellcrafter"&&level?`<fieldset class="modifier-choice-grid"><legend>${tr("builder.techniques.learnedModifications",{count:learned.length,limit:spellLimit})}</legend>${modifierIds.map(id=>`<button type="button" class="${learned.includes(id)?"on":""}" data-spellcrafter-learn="${id}">${tr(`builder.techniques.modifier.${id}`)}</button>`).join("")}</fieldset>`:"",spiritIds=["dreamy","angry","insightful","bright","kind","fierce"],wispLearned=t.id==="altruist.will-o-wisp"?[...new Set(S.mods.wispSpiritTypes||[])]:[],wispLimit=level>=3?2:level>=1?1:0,wispPicker=t.id==="altruist.will-o-wisp"&&level?`<fieldset class="modifier-choice-grid"><legend>${tr("builder.techniques.knownSpirits",{count:wispLearned.length,limit:wispLimit})}</legend>${spiritIds.map(id=>`<button type="button" class="${wispLearned.includes(id)?"on":""}" data-wisp-learn="${id}">${tr(`builder.techniques.spirit.${id}`)}</button>`).join("")}</fieldset>`:"";return `<article class="catalog-card ${level?"selected":""}"><header><div><h3>${esc(t.name)} <small>${"★".repeat(t.stars)}</small></h3><div class="meta">${esc(t.tags)}</div></div><div class="pips"><button type="button" class="pip ${level>=1?"on":""}" data-tech="${t.id}" data-level="1">1</button><button type="button" class="pip ${level>=2?"on":""}" data-tech="${t.id}" data-level="2">2</button><button type="button" class="pip ${level>=3?"on":""}" data-tech="${t.id}" data-level="3">3</button></div></header><p>${md(t.flavor)}</p><div class="tech-levels">${t.levels.map(l=>`<div class="tech-level ${level<l.n?"locked":""}"><strong>${en?"":automationBadge(techniqueLevelAutomation(t.id,l.n))}${l.n}: ${esc(l.name)}</strong><br>${md(l.text)}</div>`).join("")}</div>${spellPicker}${wispPicker}</article>`}).join("")||`<p>${tr("builder.catalog.empty")}</p>`;
}
function selectedOutlookGifts(){return activeOutlooks().filter(o=>S.outlooks.includes(o.id)).map(o=>({outlook:o,gifts:(o.builtin&&o.id===S.primaryOutlook?[o.builtin]:[]).concat(o.gifts.filter(g=>S.gifts.includes(g.id)))}));}
function renderSheet(){
  const d=derived(),en=isEnglishPreview(),attrs=en?activeAttrs():ATTRS,activeTechniqueIds=new Set(activeArchetypes().flatMap(archetype=>archetype.techniques.map(technique=>technique.id))); const techs=Object.entries(S.techniques).filter(([id,v])=>v>0&&activeTechniqueIds.has(id)).map(([id,level])=>({tech:techById(id),level})).filter(x=>x.tech);
  const words={unnamed:t("builder.hero.unnamedFull"),concept:t("builder.hero.noConcept"),player:t("builder.hero.player"),tier:t("builder.hero.tier"),stats:[[t("builder.stat.health"),d.hp],...(d.guts==null?[]:[[t("builder.stat.guts"),d.guts]]),[t("builder.stat.speed"),d.speed],[t("builder.stat.focus"),d.focus]],attrs:t("builder.sheet.attributes"),outlooks:t("builder.sheet.outlooks"),primary:t("builder.outlooks.primary"),skills:t("builder.sheet.skills"),artist:t("builder.sheet.artist"),ability:t("builder.sheet.ability"),rank:t("builder.ability.rank"),roll:t("builder.sheet.roll"),tainted:t("builder.sheet.tainted"),bonds:t("builder.sheet.bonds"),quick:t("builder.sheet.quick"),noTags:t("builder.sheet.noTags"),techniques:t("builder.sheet.techniques"),level:t("builder.sheet.level")};
  $("sheet").innerHTML=`<header>${S.media.portrait?`<img class="sheet-portrait" src="${S.media.portrait}" alt="">`:""}<div><h2>${esc(S.name||words.unnamed)}</h2><div class="sheet-sub">${esc(S.concept||words.concept)}${S.player?` · ${words.player}: ${esc(S.player)}`:""} · ${words.tier} ${S.tier}</div></div></header><div class="sheet-stats">${words.stats.map(([n,v])=>`<div class="sheet-stat"><span>${n}</span><strong>${v}</strong></div>`).join("")}</div><div class="sheet-columns"><section class="sheet-block"><h3>${words.attrs}</h3><div class="sheet-roll-list">${attrs.map(([k,n])=>`<button type="button" data-sheet-tool-attr="${k}"><span>${n}</span><strong>${attrValue(k)}D6</strong></button>`).join("")}</div></section><section class="sheet-block"><h3>${words.outlooks}</h3>${selectedOutlookGifts().map(({outlook,gifts})=>`<h4>${esc(outlook.name)}${outlook.id===S.primaryOutlook?` · ${words.primary}`:""}</h4><ul>${gifts.map(g=>`<li><strong>${esc(g.name)}</strong> — ${md(g.text)}</li>`).join("")||"<li>—</li>"}</ul>`).join("")||"<p>—</p>"}</section><section class="sheet-block"><h3>${words.skills}</h3><div class="sheet-roll-list">${S.skills.filter(s=>skillDisplayName(s).trim()).map(s=>`<button type="button" data-sheet-tool-skill="${s.id}"><span>${esc(skillDisplayName(s))}${hasGift("Performance Artist")&&S.mods.performanceSkill===s.id?` · ${words.artist}`:""}</span><strong>+${effectiveSkillRank(s)}D6</strong></button>`).join("")||"<p>—</p>"}</div>${S.ability.enabled?`<h3>${words.ability} · ${words.rank} ${S.ability.rank}</h3><p><strong>${esc(S.ability.name||abilityFormula())}</strong><br>${esc(abilityFormula())}<br>${md(S.ability.desc)}</p><button type="button" class="sheet-roll-action" data-sheet-tool-ability="main">${words.roll} · +${S.ability.rank}D6</button>`:""}${S.mods.taintedBody&&S.taintedAbility.enabled?`<h3>${words.tainted} · ${words.rank} ${S.taintedAbility.rank}</h3><p><strong>${esc(S.taintedAbility.name||abilityFormula(S.taintedAbility))}</strong><br>${esc(abilityFormula(S.taintedAbility))}<br>${md(S.taintedAbility.desc)}</p><button type="button" class="sheet-roll-action" data-sheet-tool-ability="tainted">${words.roll} · +${S.taintedAbility.rank}D6</button>`:""}</section><section class="sheet-block"><h3>${words.bonds}</h3>${S.bonds.map(bond=>`<p><strong>${esc(bond.name)} · ${words.rank} ${bond.rank}</strong>${bond.quick?` · ${words.quick}`:""}<br>${bond.tags.length?bond.tags.map(esc).join(" · "):words.noTags}</p>`).join("")||"<p>—</p>"}</section><section class="sheet-block"><h3>${words.techniques}</h3>${techs.map(({tech,level})=>`<h4>${esc(tech.name)} · ${words.level} ${level}</h4>${tech.levels.slice(0,level).map(l=>`<p><strong>${en?"":automationBadge(techniqueLevelAutomation(tech.id,l.n))}${l.n}: ${esc(l.name)}</strong> — ${md(l.text)}</p>`).join("")}`).join("")||"<p>—</p>"}</section></div>`;
}

function counter(key,label,value,max=null){return `<article class="counter"><header><span>${label}</span><span>${max===null?"":t("builder.counter.maximum",{max})}</span></header><input type="number" data-counter-input="${key}" value="${value}" min="0" ${max!==null?`max="${max}"`:""}><div class="counter-controls"><button type="button" data-counter="${key}" data-delta="-1">−</button><button type="button" data-counter="${key}" data-delta="1">+</button></div></article>`}
