"use strict";

let pendingCoreAction=null,pendingCoreActionPlan=false,pendingCoreReaction=null,pendingTechniqueRule=null,pendingTechniqueAnchor=null,pendingTechniqueOptions={},pendingTechniqueCells=[],pendingTechniqueLines=[],pendingEnemyRule=null,techniqueOrientation="horizontal";
function sceneFloatDescriptor(event){
  const payload=event.payload||{},resources={ap:"ОД",focus:"Фокус",influence:"Влияние",meals:"Трапеза",creationMarks:"Метка"};
  if(event.type==="damage.apply"){const amount=Number(payload.dealt??payload.amount??0);return{actorId:payload.targetId,text:amount?`−${amount} ЗД`:payload.evaded?`Уворот ${payload.evaded}`:"Броня",tone:amount?"damage":"guard"}}
  if(event.type==="resource.spend"&&Number(payload.amount)>0)return{actorId:event.actorId,text:`−${payload.amount} ${resources[payload.resource]||payload.resource}`,tone:"spend"};
  if(event.type==="resource.gain"&&Number(payload.amount)>0)return{actorId:event.actorId,text:`+${payload.amount} ${resources[payload.resource]||payload.resource}`,tone:"gain"};
  if(event.type==="effect.apply"){const name=D.effects.positive.concat(D.effects.negative).find(effect=>effect.id===payload.effect)?.name||payload.effect;return{actorId:payload.targetId,text:name,tone:"effect"}}
  if(event.type==="actor.heal")return{actorId:payload.targetId,text:`+${payload.restored??payload.amount??0} ЗД`,tone:"gain"};
  if(event.type==="actor.knockout")return{actorId:payload.targetId,text:"ВНЕ БОЯ",tone:"damage"};
  if(event.type==="rule.prompt")return{actorId:event.actorId,text:"СРАБОТАЛО",tone:"turn"};
  if(event.type==="turn.start")return{actorId:event.actorId,text:"ВАШ ХОД",tone:"turn"};
  if(event.type==="turn.grant")return{actorId:event.actorId,text:"ЕЩЕ ХОД",tone:"turn"};
  if(event.type==="technique.state")return{actorId:event.actorId,text:payload.key==="study"?"+1 ПЛАН":`${Number(payload.delta||0)>0?"+":""}${payload.delta||0} ПЛАН`,tone:Number(payload.delta||1)>0?"gain":"spend"};
  if(event.type==="actor.state")return{actorId:event.actorId,text:payload.key==="growth"?"+1 РОСТ":"СОСТОЯНИЕ",tone:"effect"};
  if(event.type==="roll.public")return{actorId:event.actorId,text:`${payload.successes||0} усп.`,tone:"roll"};
  return null;
}
function spawnSceneFloat(event,lane=0){
  const item=sceneFloatDescriptor(event),wrap=$("scene-board-wrap");if(!item||!wrap)return;const token=wrap.querySelector(`[data-scene-actor="${CSS.escape(item.actorId||"")}"]`);if(!token)return;
  const tokenRect=token.getBoundingClientRect(),wrapRect=wrap.getBoundingClientRect(),node=document.createElement("span");node.className=`scene-float-text ${item.tone}`;node.textContent=item.text;node.style.left=`${tokenRect.left-wrapRect.left+wrap.scrollLeft+tokenRect.width/2}px`;node.style.top=`${tokenRect.top-wrapRect.top+wrap.scrollTop-4-Math.min(lane,3)*12}px`;wrap.append(node);setTimeout(()=>node.remove(),1350);
}
function playSceneEventFx(events=[]){
  const actorFx=new Map(),add=(id,name)=>{if(!id)return;const set=actorFx.get(id)||new Set();set.add(name);actorFx.set(id,set)};
  let boardFx="";
  for(const event of events){
    const payload=event.payload||{},participants=SceneEngine.eventParticipants(Scene,event);
    for(const id of participants.sourceIds){add(id,"fx-involved");add(id,"fx-involved-source")}
    for(const id of participants.targetIds){add(id,"fx-involved");add(id,"fx-involved-target")}
    if(event.type==="action.prepare"||event.type==="enemy.action.prepare"||event.type==="technique.prepare"){add(event.actorId,"fx-action");boardFx="fx-cast"}else if(event.type==="reaction.offer")add(event.actorId,"fx-reaction");else if(event.type==="reaction.respond")add(event.actorId,"fx-response");else if(event.type==="damage.apply"||event.type==="actor.knockout")add(payload.targetId,"fx-damage");else if(event.type==="actor.heal")add(payload.targetId,"fx-gain");else if(event.type==="resource.gain"||event.type==="technique.state"||event.type==="actor.state")add(event.actorId,"fx-gain");else if(event.type==="actor.move")add(event.actorId,"fx-move");else if(event.type==="turn.start"||event.type==="turn.grant")add(event.actorId,"fx-turn");else if(event.type==="roll.public")boardFx="fx-roll"
  }
  requestAnimationFrame(()=>{const touched=[];for(const[id,names]of actorFx){const token=document.querySelector(`[data-scene-actor="${CSS.escape(id)}"]`);if(!token)continue;for(const name of names)token.classList.add(name);touched.push(token)}const board=$("scene-board-wrap");if(boardFx&&board){board.classList.add(boardFx);touched.push(board)}const latest=$("scene-roll-feed")?.querySelector("article");if(events.some(event=>event.type==="roll.public")&&latest){latest.classList.add("fx-enter");touched.push(latest)}events.forEach(spawnSceneFloat);setTimeout(()=>touched.forEach(node=>node.classList.remove("fx-action","fx-reaction","fx-response","fx-damage","fx-gain","fx-move","fx-turn","fx-cast","fx-roll","fx-enter","fx-involved","fx-involved-source","fx-involved-target")),1450)})
}
function sceneFlowSteps(labels,current){return `<ol class="scene-flow-steps">${labels.map((label,index)=>`<li class="${index<current?"done":index===current?"current":""}"><i>${index<current?"✓":index+1}</i><span>${esc(label)}</span></li>`).join("")}</ol>`}
function rulePromptChoiceLabel(prompt,choice){const names={"pure-water":"Чистая вода","rage-fumes":"Пары ярости","growth-serum":"Сыворотка роста",adrenaline:"Адреналиновый стимулятор","stone-skin":"Бальзам каменной кожи","thorn-rot":"Яд мерзошипа",attack:"Быстрая Стычка",pass:"Не использовать",transform:"Трансформироваться",rush:"Переместиться",stop:"Остановить",single:"Оставить один Дух",cancel:"Отменить"};const spirits={dreamy:"Мечтательный дух",angry:"Злой дух",insightful:"Проницательный дух",bright:"Яркий дух",kind:"Добрый дух",fierce:"Яростный дух"};if(names[choice])return names[choice];if(spirits[choice])return spirits[choice];if(choice.startsWith("combine:"))return `Объединить: ${spirits[choice.slice(8)]||choice.slice(8)}`;if(choice.startsWith("split:"))return `Два Пламени: ${spirits[choice.slice(6)]||choice.slice(6)}`;const marker=Scene.markers.find(item=>item.id===choice);if(marker)return marker.label;return D.effects.positive.concat(D.effects.negative).find(effect=>effect.id===choice)?.name||choice}
function cancelSceneFlow(){pendingCoreAction=null;pendingCoreActionPlan=false;pendingCoreReaction=null;pendingTechniqueRule=null;pendingTechniqueAnchor=null;pendingTechniqueOptions={};pendingTechniqueCells=[];pendingTechniqueLines=[];pendingEnemyRule=null;scenePreviewCells.clear();sceneMeasureStart=null;sceneMeasureCells.clear();sceneMeasureLabel="";Scene.tool="select";persist();renderScene();toast("Подготовка действия отменена")}
function cancelCommittedAction(reason="Цепочка прервана Нарратором"){const prepared=SceneEngine.cancelPendingAction(Scene,{reason});if(!prepared.ok)return toast(prepared.errors.join(" "));if(commitSceneEvents("Цепочка Атаки прервана",prepared.events))toast("Цепочка закрыта без урона")}
function resolveCommittedAction(){const prepared=SceneEngine.resolvePendingAction(Scene,D);if(!prepared.ok)return toast(prepared.errors.join(" "));const label=prepared.cancelled?"Цепочка Атаки прервана":"Атака разрешена";if(commitSceneEvents(label,prepared.events))toast(prepared.cancelled?"Цепочка закрыта без урона":"Цепочка действия завершена: урон и Эффекты применены")}
function renderSceneFlow(){
  const root=$("scene-flow"),active=Scene.actors.find(actor=>actor.id===Scene.activeActorId),prompt=Scene.pendingPrompt,pending=Scene.pendingAction,pendingStatus=SceneEngine.pendingActionStatus(Scene),roundStatus=SceneEngine.roundEndStatus(Scene),roundStarted=Scene.actors.some(actor=>actor.acted),compactLandscape=matchMedia("(max-width:950px) and (max-height:500px) and (orientation:landscape)").matches;let phase="turn",title="Ход не начат",hint=activeSceneView()==="gm"?(roundStarted?(roundStatus.available?"Все обязательные Ходы завершены — можно начать новый Раунд.":roundStatus.reason):"Выберите участника в ленте ходов."):"Нарратор ещё не начал Ход.",steps=sceneFlowSteps(["Начать Ход","Выбрать действие"],0),actions="";
  if(prompt){const placement=["marker-move-cell","empath-rush-cell","reappear-cell"].includes(prompt.kind);phase=placement?"destination":"reaction";title=prompt.title||"Сработало правило";hint=prompt.text||"Выберите, как разрешить сработавшее правило.";steps=sceneFlowSteps(["Триггер",placement?"Клетка":"Решение","Последствие"],1);actions=placement?`<button type="button" data-rule-prompt-choice="cancel">Отменить</button>`:(prompt.options||[]).map(choice=>`<button type="button" class="${["attack","transform","rush","stop"].includes(choice)?"primary":""}" data-rule-prompt-choice="${esc(choice)}">${esc(rulePromptChoiceLabel(prompt,choice))}</button>`).join("")}
  else if(pending){const waiting=pendingStatus.waitingIds,answered=pendingStatus.answeredIds.length,total=pendingStatus.eligibleIds.length,skipped=pendingStatus.unavailableIds.length,target=Scene.actors.find(actor=>actor.id===waiting[0]),gm=activeSceneView()==="gm";if(pendingStatus.mustCancel){phase="interrupted";title=`«${pending.name}» прервано`;hint=pendingStatus.interruptedReason||"Все цели уже недоступны. Закройте цепочку без урона.";steps=sceneFlowSteps(["Действие","Цели","Прервано"],2);actions=gm?`<button type="button" class="primary" data-core-cancel-pending>Закрыть цепочку</button>`:""}else{phase=waiting.length?"reaction":"resolve";title=waiting.length?`Реакция: ${target?.name||"цель"}`:`«${pending.name}» готово к разрешению`;hint=waiting.length?`Ответы ${answered}/${total}.${skipped?` Недоступных целей: ${skipped}.`:""} Выберите защиту — её эффект будет показан до урона.`:`Все доступные цели ответили.${skipped?` Будет пропущено целей: ${skipped}.`:""} Нарратор может применить бросок и урон.`;steps=sceneFlowSteps(["Действие","Цели","Бросок",`Реакции ${answered}/${total}`,"Урон"],waiting.length?3:4);actions=`<button type="button" data-open-scene-panel="sheet">${waiting.length?"Открыть Реакции":"Проверить исход"}</button>${gm?`<button type="button" ${waiting.length?`class="danger-quiet" data-core-cancel-pending`:`class="primary" data-core-resolve`}>${waiting.length?"Прервать":"Разрешить"}</button>`:""}`}}
  else if(pendingCoreReaction){const actor=Scene.actors.find(item=>item.id===pendingCoreReaction.actorId);phase="destination";title=`Уворот: ${actor?.name||"цель"}`;hint="Выберите свободную клетку в пределах 2 клеток. Допустимый итог сразу появится в журнале.";steps=sceneFlowSteps(["Реакция","Клетка","Подтвердить"],1);actions=`<button type="button" data-scene-flow-cancel>Отменить</button>`}
  else if(pendingCoreAction){const action=D.actions.list.find(item=>item.id===pendingCoreAction),actor=currentHeroActor(),appearance=["Стычка","Заклинание","Завершение"].includes(action?.name)&&sceneActorEffects(actor).includes("positive.исчез"),continuing=action?.name==="Шаг"&&(actor?.usedActions||[]).includes(action.id)&&Number(actor?.stepRemaining||0)>0,baseLimit=action?.name==="Прыжок"?Number(actor?.attrs?.talent||0):continuing?Number(actor?.stepRemaining||0):Number(actor?.speed||0),limit=sceneActorEffects(actor).includes("positive.ускорен")?baseLimit*2:sceneActorEffects(actor).includes("negative.замедлен")?Math.floor(baseLimit/2):baseLimit;phase="destination";title=appearance?`Ликвидация: клетка появления`:`${continuing?"Продолжить Шаг":action?.name||"Перемещение"}: клетка назначения`;hint=appearance?"Выберите любую пустую клетку: «Ликвидация» разрешает появиться и рядом с персонажем. После выбора начнётся Атака с преимуществом Ступени и критами на 5–6.":`Подсвечены свободные клетки в пределах ${limit}${action?.name==="Прыжок"?" по прямой Линии":""}. ${continuing?"ОД уже потрачено; используется сохранённое движение.":"Ресурс спишется после корректного выбора."}`;steps=sceneFlowSteps(["Действие","Клетка","Готово"],1);actions=`<button type="button" data-scene-flow-cancel>Отменить</button>`}
  else if(pendingEnemyRule){const actor=Scene.actors.find(item=>item.id===pendingEnemyRule.actorId),rule=enemyProfile(actor?.profileId)?.rules?.find(item=>item.id===pendingEnemyRule.ruleId);phase="area";title=`${rule?.name||"Действие врага"}: область`;hint="Наведите на поле, проверьте подсветку и выберите центр области.";steps=sceneFlowSteps(["Действие","Область","Цели","Реакции"],1);actions=`<button type="button" data-scene-flow-cancel>Отменить</button>`}
  else if(pendingTechniqueRule){const nails=pendingTechniqueRule.form==="nails",idol=pendingTechniqueRule.form==="idol";phase="area";title=`Техника: ${pendingTechniqueRule.name}`;hint=nails?`Выберите две пересекающиеся Линии длиной 3. Выбрано: ${pendingTechniqueLines.length}/2 · R меняет направление.`:idol?`Выберите 1–6 связанных клеток. Выбрано: ${pendingTechniqueCells.length}.`:`Выберите клетку${pendingTechniqueRule.shape==="line"?"; клавиша R поворачивает линию":""}. До подтверждения ресурсы не расходуются.`;steps=sceneFlowSteps(["Техника","Позиция","Эффект"],1);actions=`${idol?`<button type="button" class="primary" data-confirm-technique-cells ${pendingTechniqueCells.length?"":"disabled"}>Подтвердить клетки</button>`:""}<button type="button" data-scene-flow-cancel>Отменить</button>`}
  else if(active){phase="action";title=`Ход: ${active.name}`;hint=active.team==="enemy"?(compactLandscape?"Откройте «Цель» или «Враги».":"Выберите действие противника в панели цели или отряда."):active.heroId===S.id?"Выберите базовое действие или Технику. Цели отмечаются прямо на поле.":"Ожидается действие текущего участника.";steps=sceneFlowSteps(["Ход начат","Действие","Цели и исход","Завершить Ход"],1);actions=active.heroId===S.id?`<button type="button" data-open-scene-panel="sheet">Открыть действия</button>`:""}
  root.dataset.phase=phase;root.innerHTML=`<div class="scene-flow-copy"><span>${phase==="reaction"?"ОЖИДАЕТСЯ ОТВЕТ":phase==="resolve"?"ГОТОВО К УРОНУ":phase==="interrupted"?"ЦЕПОЧКА ПРЕРВАНА":"ТЕКУЩИЙ ЭТАП"}</span><strong>${esc(title)}</strong><small>${esc(hint)}</small></div>${steps}<div class="scene-flow-actions">${actions}</div>`;
}
