"use strict";

let pendingCoreAction=null,pendingCoreActionPlan=false,pendingCoreActionContext=null,pendingCoreActorId=null,pendingCoreReaction=null,pendingTechniqueRule=null,pendingTechniqueAnchor=null,pendingTechniqueOptions={},pendingTechniqueCells=[],pendingTechniqueLines=[],pendingEnemyRule=null,pendingEnemyStepActorId=null,pendingZealotPlan=null,techniqueOrientation="horizontal";
function sceneFloatDescriptor(event){
  const payload=event.payload||{},resources={ap:"ОД",focus:"Фокус",influence:"Влияние",meals:"Трапеза",creationMarks:"Метка","creation-marks":"Метки",bullets:"Пули",weapons:"Оружие",heat:"Нагрев",grit:"Упорство",faith:"Вера",health:"Здоровье"},resolved=payload.resolvedResource||payload.resource,delta=Number(payload.resolvedDelta);
  if(event.type==="damage.apply"){const amount=Number(payload.dealt??payload.amount??0);return{actorId:payload.targetId,text:amount?`−${amount} ЗД`:payload.evaded?`Уворот ${payload.evaded}`:"Броня",tone:amount?"damage":"guard"}}
  if(["resource.spend","resource.gain","rule-resource.spend","rule-resource.gain"].includes(event.type)&&Number(payload.amount)>0){const signed=Number.isFinite(delta)?delta:(event.type.endsWith(".gain")?1:-1)*Number(payload.amount);if(!signed)return null;return{actorId:event.actorId,text:`${signed>0?"+":"−"}${Math.abs(signed)} ${resources[resolved]||resolved}`,tone:signed>0?"gain":"spend"}}
  if(event.type==="effect.apply"){const name=D.effects.positive.concat(D.effects.negative).find(effect=>effect.id===payload.effect)?.name||payload.effect;return{actorId:payload.targetId,text:name,tone:"effect"}}
  if(event.type==="effect.remove"&&payload.removed){const name=D.effects.positive.concat(D.effects.negative).find(effect=>effect.id===payload.effect)?.name||payload.effect;return{actorId:payload.targetId,text:`− ${name}`,tone:"guard"}}
  if(event.type==="actor.heal")return{actorId:payload.targetId,text:`+${payload.restored??payload.amount??0} ЗД`,tone:"gain"};
  if(event.type==="actor.knockout")return{actorId:payload.targetId,text:"ВНЕ БОЯ",tone:"damage"};
  if(event.type==="rule.prompt")return{actorId:event.actorId,text:"СРАБОТАЛО",tone:"turn"};
  if(event.type==="turn.start")return{actorId:event.actorId,text:"ВАШ ХОД",tone:"turn"};
  if(event.type==="turn.grant")return{actorId:event.actorId,text:"ЕЩЕ ХОД",tone:"turn"};
  if(event.type==="technique.state")return{actorId:event.actorId,text:payload.key==="study"?"+1 ПЛАН":`${Number(payload.delta||0)>0?"+":""}${payload.delta||0} ПЛАН`,tone:Number(payload.delta||1)>0?"gain":"spend"};
  if(event.type==="actor.state")return{actorId:event.actorId,text:payload.key==="growth"?"+1 РОСТ":"СОСТОЯНИЕ",tone:"effect"};
  if(event.type==="roll.public")return{actorId:event.actorId,text:`${payload.successes||0} усп.`,tone:"roll"};
  return null;
}
function spawnSceneFloat(event,lane=0){
  const item=sceneFloatDescriptor(event),wrap=$("scene-board-wrap");if(!item||!wrap)return;const token=wrap.querySelector(`[data-scene-actor="${CSS.escape(item.actorId||"")}"]`);if(!token)return;
  const tokenRect=token.getBoundingClientRect(),wrapRect=wrap.getBoundingClientRect(),node=document.createElement("span");node.className=`scene-float-text ${item.tone}`;node.textContent=item.text;node.style.left=`${tokenRect.left-wrapRect.left+wrap.scrollLeft+tokenRect.width/2}px`;node.style.top=`${tokenRect.top-wrapRect.top+wrap.scrollTop-4-Math.min(lane,3)*12}px`;wrap.append(node);setTimeout(()=>node.remove(),1350);
}
function innerWorldEvent(events=[]){
  const ensure=events.find(event=>event.type==="space.ensure"&&event.payload?.activate&&(/Внутренний мир/.test(event.payload.name||"")||event.payload?.ruleId==="disruptor.inner-world.2"));
  const marked=events.some(event=>event.payload?.sourceActionId==="disruptor.inner-world.2"||event.payload?.ruleId==="disruptor.inner-world.2");
  return ensure&&marked?ensure:null;
}
function playInnerWorldFx(events=[],context={}){
  const ensure=innerWorldEvent(events);
  if(!ensure)return;
  const wrap=$("scene-board-wrap"),caster=events.find(event=>event.type==="technique.prepare"&&event.payload?.ruleId==="disruptor.inner-world.2")?.actorId||events.find(event=>event.payload?.sourceActionId==="disruptor.inner-world.2")?.actorId;
  if(!wrap||!caster)return;
  const movers=[...new Set(events.filter(event=>event.type==="actor.move"&&event.payload?.space===ensure.payload.id).map(event=>event.actorId))],target=movers.find(id=>id!==caster);
  if(!target)return;
  const locate=id=>wrap.querySelector(`[data-scene-actor="${CSS.escape(id)}"]`)?.getBoundingClientRect();
  const wrapRect=wrap.getBoundingClientRect(),heroRect=locate(caster),enemyRect=locate(target),fallback={x:wrap.clientWidth/2,y:wrap.clientHeight/2};
  const point=(rect,id)=>context.points?.[id]||(rect?{x:rect.left-wrapRect.left+wrap.scrollLeft+rect.width/2,y:rect.top-wrapRect.top+wrap.scrollTop+rect.height/2}:fallback);
  const overlay=document.createElement("div");overlay.className="inner-world-fx";overlay.setAttribute("aria-hidden","true");
  const voidNode=document.createElement("i");voidNode.className="inner-world-fx-void";
  const beam=document.createElement("i");beam.className="inner-world-fx-beam";
  overlay.append(voidNode,beam);wrap.append(overlay);
  const hero=point(heroRect,caster),enemy=point(enemyRect,target),size=Math.max(56,Math.min(wrapRect.width,wrapRect.height)*.18);
  voidNode.style.setProperty("--iw-x",`${hero.x}px`);voidNode.style.setProperty("--iw-y",`${hero.y}px`);voidNode.style.setProperty("--iw-size",`${size}px`);voidNode.style.setProperty("--iw-enemy-x",`${enemy.x}px`);voidNode.style.setProperty("--iw-enemy-y",`${enemy.y}px`);
  beam.style.left=`${hero.x}px`;beam.style.top=`${hero.y}px`;beam.style.width=`${Math.hypot(enemy.x-hero.x,enemy.y-hero.y)}px`;beam.style.setProperty("--iw-angle",`${Math.atan2(enemy.y-hero.y,enemy.x-hero.x)}rad`);
  const casterToken=wrap.querySelector(`[data-scene-actor="${CSS.escape(caster)}"]`),targetToken=wrap.querySelector(`[data-scene-actor="${CSS.escape(target)}"]`);casterToken?.classList.add("fx-inner-world-caster");targetToken?.classList.add("fx-inner-world-target");
  wrap.classList.add("fx-inner-world");
  const cleanup=()=>{overlay.remove();wrap.classList.remove("fx-inner-world");casterToken?.classList.remove("fx-inner-world-caster");targetToken?.classList.remove("fx-inner-world-target")};
  const reduced=window.matchMedia?.("(prefers-reduced-motion: reduce)")?.matches;
  if(reduced){overlay.classList.add("reduced");setTimeout(cleanup,260)}else setTimeout(cleanup,3600);
}
function playInnerWorldExitFx(events=[],context={}){
  const exit=events.find(event=>event.type==="technique.resolve"&&event.payload?.innerWorldExit&&event.payload?.sourceActionId==="disruptor.inner-world.2");
  if(!exit)return;
  const wrap=$("scene-board-wrap"),movers=events.filter(event=>event.type==="actor.move"&&event.payload?.innerWorldExit).map(event=>event.actorId);
  if(!wrap||!movers.length)return;
  const wrapRect=wrap.getBoundingClientRect(),points=movers.map(id=>({id,rect:wrap.querySelector(`[data-scene-actor="${CSS.escape(id)}"]`)?.getBoundingClientRect()})).filter(item=>item.rect);
  if(!points.length)return;
  const overlay=document.createElement("div");overlay.className="inner-world-exit-fx";overlay.setAttribute("aria-hidden","true");wrap.append(overlay);
  const center=points.reduce((sum,item)=>({x:sum.x+item.rect.left-wrapRect.left+item.rect.width/2,y:sum.y+item.rect.top-wrapRect.top+item.rect.height/2}),{x:0,y:0});center.x/=points.length;center.y/=points.length;
  overlay.style.setProperty("--iw-exit-x",`${center.x}px`);overlay.style.setProperty("--iw-exit-y",`${center.y}px`);
  const tokens=points.map(item=>wrap.querySelector(`[data-scene-actor="${CSS.escape(item.id)}"]`)).filter(Boolean);tokens.forEach(token=>token.classList.add("fx-inner-world-exit"));
  wrap.classList.add("fx-inner-world-exit-board");
  const cleanup=()=>{overlay.remove();wrap.classList.remove("fx-inner-world-exit-board");tokens.forEach(token=>token.classList.remove("fx-inner-world-exit"))};
  const reduced=window.matchMedia?.("(prefers-reduced-motion: reduce)")?.matches;setTimeout(cleanup,reduced?260:1900);
}
function playSceneEventFx(events=[],context={}){
  const actorFx=new Map(),add=(id,name)=>{if(!id)return;const set=actorFx.get(id)||new Set();set.add(name);actorFx.set(id,set)};
  let boardFx="";
  for(const event of events){
    const payload=event.payload||{},participants=SceneEngine.eventParticipants(Scene,event);
    for(const id of participants.sourceIds){add(id,"fx-involved");add(id,"fx-involved-source")}
    for(const id of participants.targetIds){add(id,"fx-involved");add(id,"fx-involved-target")}
    if(event.type==="action.prepare"||event.type==="enemy.action.prepare"||event.type==="technique.prepare"){add(event.actorId,"fx-action");boardFx="fx-cast"}else if(event.type==="reaction.offer")add(event.actorId,"fx-reaction");else if(event.type==="reaction.respond")add(event.actorId,"fx-response");else if(event.type==="damage.apply"||event.type==="actor.knockout")add(payload.targetId,"fx-damage");else if(event.type==="actor.heal"||event.type==="effect.apply")add(payload.targetId,"fx-gain");else if(event.type==="effect.remove")add(payload.targetId,"fx-response");else if(["resource.gain","rule-mode.set","rule-resource.gain","rule-resource.set","rule-resource.reset","rule-clock.configure","rule-clock.tick","rule-clock.set","rule-clock.reset","technique.state","actor.state"].includes(event.type))add(event.actorId,Number(payload.appliedDelta||payload.delta||0)<0?"fx-spend":"fx-gain");else if(event.type==="actor.move")add(event.actorId,"fx-move");else if(event.type==="topology.cells.remove"||event.type==="topology.cells.restore")boardFx="fx-topology";else if(event.type==="turn.start"||event.type==="turn.grant")add(event.actorId,"fx-turn");else if(event.type==="roll.public")boardFx="fx-roll"
  }
  requestAnimationFrame(()=>{playInnerWorldFx(events,context);playInnerWorldExitFx(events,context);const touched=[];for(const[id,names]of actorFx){const token=document.querySelector(`[data-scene-actor="${CSS.escape(id)}"]`);if(!token)continue;for(const name of names)token.classList.add(name);touched.push(token)}const board=$("scene-board-wrap");if(boardFx&&board){board.classList.add(boardFx);touched.push(board)}const latest=$("scene-roll-feed")?.querySelector("article:last-child");if(events.some(event=>event.type==="roll.public")&&latest){latest.classList.add("fx-enter");touched.push(latest)}events.forEach(spawnSceneFloat);setTimeout(()=>touched.forEach(node=>node.classList.remove("fx-action","fx-reaction","fx-response","fx-damage","fx-gain","fx-move","fx-turn","fx-cast","fx-roll","fx-topology","fx-enter","fx-involved","fx-involved-source","fx-involved-target")),1450)})
}
function sceneFlowSteps(labels,current){return `<ol class="scene-flow-steps">${labels.map((label,index)=>`<li class="${index<current?"done":index===current?"current":""}"><i>${index<current?"✓":index+1}</i><span>${esc(label)}</span></li>`).join("")}</ol>`}
function rulePromptChoiceLabel(prompt,choice){const names={"pure-water":"Чистая вода","rage-fumes":"Пары ярости","growth-serum":"Сыворотка роста",adrenaline:"Адреналиновый стимулятор","stone-skin":"Бальзам каменной кожи","thorn-rot":"Яд мерзошипа",attack:"Быстрая Стычка",pass:"Не использовать",accept:"Принять перенаправление",resist:"Сопротивляться (+2 Стресса)",place:"Поставить Слабую точку",study:"Изучить атакующего",stun:"Наложить Ошеломлен",transform:"Трансформироваться",rush:"Переместиться",pull:"Притянуть",stop:"Остановить",continue:"Продолжить",convert:"Преобразовать Сосульку",finale:"Использовать Финал",single:"Оставить один Дух",cancel:"Отменить",fill:"Заполнить",invoke:"Использовать",flow:"Получить ОД и переместиться",provoke:"Наложить Спровоцирован",frighten:"Наложить Испуган","hold-back":"Сдержаться",disappear:"Исчезнуть",reapply:"Применить снова"};const spirits={dreamy:"Мечтательный дух",angry:"Злой дух",insightful:"Проницательный дух",bright:"Пылкий дух",kind:"Добрый дух",fierce:"Яростный дух"};if(prompt.context?.optionLabels?.[choice])return prompt.context.optionLabels[choice];if(names[choice])return names[choice];if(spirits[choice])return spirits[choice];if(choice.startsWith("cell:")){const[x,y]=choice.slice(5).split(",").map(Number);return `Клетка ${String.fromCharCode(65+x)}${y+1}`}if(choice.startsWith("combine:"))return `Объединить: ${spirits[choice.slice(8)]||choice.slice(8)}`;if(choice.startsWith("split:"))return `Два Пламени: ${spirits[choice.slice(6)]||choice.slice(6)}`;const marker=Scene.markers.find(item=>item.id===choice);if(marker)return `${marker.label} · ${String.fromCharCode(65+Number(marker.x))}${Number(marker.y)+1}`;const actor=Scene.actors.find(item=>item.id===choice);if(actor)return actor.name;return D.effects.positive.concat(D.effects.negative).find(effect=>effect.id===choice)?.name||choice}
function cancelSceneFlow(){if(Scene.pendingActionPlan){const prepared=SceneEngine.cancelActionPlan(Scene,{actorId:Scene.pendingActionPlan.actorId,reason:"Отменено до оплаты и применения."});if(!prepared.ok)return toast(prepared.errors.join(" "));if(!commitSceneEvents(`Отмена: ${Scene.pendingActionPlan.actionName}`,prepared.events))return}pendingCoreAction=null;pendingCoreActionPlan=false;pendingCoreActionContext=null;pendingCoreActorId=null;pendingCoreReaction=null;pendingTechniqueRule=null;pendingTechniqueAnchor=null;pendingTechniqueOptions={};pendingTechniqueCells=[];pendingTechniqueLines=[];pendingEnemyRule=null;pendingEnemyStepActorId=null;pendingZealotPlan=null;scenePreviewCells.clear();sceneTopologyCells.clear();sceneMeasureStart=null;sceneMeasureCells.clear();sceneMeasureLabel="";Scene.tool="select";persist();renderScene();toast("Подготовка действия отменена без затрат")}
function changeSceneTool(requested){
  const localFlow=Boolean(Scene.pendingActionPlan||pendingCoreAction||pendingCoreReaction||pendingTechniqueRule||pendingEnemyRule||pendingEnemyStepActorId||pendingZealotPlan);
  if(localFlow)cancelSceneFlow();
  const current=activeSceneTool(),toggleOff=requested===current&&requested==="target";
  if(activeSceneView()==="player")playerSceneTool=toggleOff?"select":requested;else Scene.tool=toggleOff?"select":requested;
  if(toggleOff||!["select","target","measure"].includes(requested)){Scene.targetIds=[];Scene.targetCells=[]}
  scenePreviewCells.clear();sceneTopologyCells.clear();sceneMeasureStart=null;sceneMeasureCells.clear();sceneMeasureLabel=activeSceneTool()==="measure"?"Линейка: выберите начальную клетку":"";
  persist();renderScene();
}
function cancelCommittedAction(reason="Цепочка прервана Нарратором"){const prepared=SceneEngine.cancelPendingAction(Scene,{reason});if(!prepared.ok)return toast(prepared.errors.join(" "));if(commitSceneEvents("Цепочка Атаки прервана",prepared.events))toast("Цепочка закрыта без урона")}
function resolveCommittedAction(){const prepared=SceneEngine.resolvePendingAction(Scene,D);if(!prepared.ok)return toast(prepared.errors.join(" "));const label=prepared.cancelled?"Цепочка Атаки прервана":"Атака разрешена";if(commitSceneEvents(label,prepared.events))toast(prepared.cancelled?"Цепочка закрыта без урона":"Цепочка действия завершена: урон и Эффекты применены")}
function renderSceneFlow(){
  const root=$("scene-flow"),active=Scene.actors.find(actor=>actor.id===Scene.activeActorId),prompt=Scene.pendingPrompt,pending=Scene.pendingAction,pendingStatus=SceneEngine.pendingActionStatus(Scene,D),triggerQueue=SceneEngine.triggerQueueStatus(Scene),roundStatus=SceneEngine.roundEndStatus(Scene),roundStarted=Scene.actors.some(actor=>actor.acted),readyActors=Scene.actors.filter(actor=>!actor.knockedOut&&!actor.acted),heroes=Scene.actors.filter(actor=>actor.team==="hero"&&actor.kind!=="token"),enemies=Scene.actors.filter(actor=>actor.team==="enemy"&&actor.kind!=="token"),heroesDown=heroes.length>0&&heroes.every(actor=>actor.knockedOut),enemiesDown=enemies.length>0&&enemies.every(actor=>actor.knockedOut),battleOutcome=heroes.length&&enemies.length?(heroesDown&&enemiesDown?"draw":enemiesDown?"victory":heroesDown?"defeat":null):null,gm=activeSceneView()==="gm",compactLandscape=matchMedia("(max-width:950px) and (max-height:500px) and (orientation:landscape)").matches;let phase="turn",title="Ход не начат",hint=gm?(roundStarted?(roundStatus.available?"Все обязательные Ходы завершены — можно начать новый Раунд.":roundStatus.reason):"Выберите участника в ленте ходов."):"Нарратор ещё не начал Ход.",steps=sceneFlowSteps(["Начать Ход","Выбрать действие"],0),actions="";
  if(!Scene.actors.length){phase="setup";title="Подготовьте столкновение";hint=gm?"Добавьте героев и противников, расставьте токены и начните Ход любого участника.":"Нарратор готовит участников и поле.";steps=sceneFlowSteps(["Участники","Расстановка","Первый Ход"],0);actions=gm?`<button type="button" class="primary" data-open-scene-panel="add">Добавить участников</button>`:""}
  else if(roundStatus.available){phase="round";title=`Раунд ${Scene.round} завершён`;hint="Все обязательные Ходы сыграны. Новый Раунд повысит Напряжение и восстановит ОД.";steps=sceneFlowSteps(["Все Ходы","Конец Раунда","Новый Раунд"],1);actions=gm?`<button type="button" class="primary" data-scene-flow-round>Начать Раунд ${Scene.round+1}</button>`:""}
  else if(!active&&gm){title=readyActors.length?"Кто действует следующим?":"Проверьте состояние Раунда";hint=readyActors.length?`Готовы: ${readyActors.map(actor=>actor.name).join(", ")}. В DAWN порядок выбирает стол — нажмите участника в ленте или откройте пульт.`:(roundStatus.reason||"Откройте пульт Нарратора для ручного решения.");actions=`<button type="button" data-scene-flow-director>Открыть пульт</button>`}
  if(prompt){const placement=["marker-move-cell","dim-mak-weak-point-cell","empath-rush-cell","reappear-cell","knife-pickup-step","meister-overclock-move","egomaniac-style-move","thunder-surge-cell","siren-irresistible-cell","untouchable-weave-cell","constrictor-move-cell","enemy-move-cell"].includes(prompt.kind),innerWorldPlacement=["inner-world-target-cell","inner-world-caster-cell"].includes(prompt.kind),controlled=canControlScenePrompt(prompt),marker=placement&&Scene.markers.find(item=>item.id===prompt.context?.markerId);phase=placement||innerWorldPlacement?"destination":"reaction";title=prompt.title||"Сработало правило";hint=controlled?`${marker?`${marker.label}: `:""}${prompt.text||"Выберите, как разрешить сработавшее правило."}${placement||innerWorldPlacement?" Допустимые клетки подсвечены прямо на поле.":""}${triggerQueue.count?` После ответа в очереди: ${triggerQueue.count}.`:""}`:prompt.controller==="narrator"?"Решение принимает Нарратор.":`Решение принимает ${Scene.actors.find(actor=>actor.id===prompt.sourceActorId)?.name||"другой участник"}.`;steps=sceneFlowSteps(innerWorldPlacement?["Активировать","Противник","Инициатор"]:["Триггер",placement?"Клетка":"Решение",triggerQueue.count?`Последствие · ещё ${triggerQueue.count}`:"Последствие"],innerWorldPlacement?1:1);actions=!controlled?"":placement||innerWorldPlacement?`<button type="button" data-rule-prompt-choice="cancel">Отменить</button>`:(prompt.options||[]).map(choice=>`<button type="button" class="${["attack","transform","rush","stop","study","stun","place","accept","pull"].includes(choice)?"primary":""}" data-rule-prompt-choice="${esc(choice)}">${esc(rulePromptChoiceLabel(prompt,choice))}</button>`).join("")}
  else if(pending){const waiting=pendingStatus.waitingIds,answered=pendingStatus.answeredIds.length,total=pendingStatus.eligibleIds.length,skipped=pendingStatus.unavailableIds.length,target=Scene.actors.find(actor=>actor.id===waiting[0]),gm=activeSceneView()==="gm";if(pendingStatus.mustCancel){phase="interrupted";title=`«${pending.name}» прервано`;hint=pendingStatus.interruptedReason||"Все цели уже недоступны. Закройте цепочку без урона.";steps=sceneFlowSteps(["Действие","Цели","Прервано"],2);actions=gm?`<button type="button" class="primary" data-core-cancel-pending>Закрыть цепочку</button>`:""}else{phase=waiting.length?"reaction":"resolve";title=waiting.length?`Реакция: ${target?.name||"цель"}`:`«${pending.name}» готово к разрешению`;hint=waiting.length?`Ответы ${answered}/${total}.${skipped?` Недоступных целей: ${skipped}.`:""} Выберите защиту — её эффект будет показан до урона.`:`Все доступные цели ответили.${skipped?` Будет пропущено целей: ${skipped}.`:""} Нарратор может применить бросок и урон.`;steps=sceneFlowSteps(["Действие","Цели","Бросок",`Реакции ${answered}/${total}`,"Урон"],waiting.length?3:4);actions=`<button type="button" data-open-scene-panel="sheet">${waiting.length?"Открыть Реакции":"Проверить исход"}</button>${gm?`<button type="button" ${waiting.length?`class="danger-quiet" data-core-cancel-pending`:`class="primary" data-core-resolve`}>${waiting.length?"Прервать":"Разрешить"}</button>`:""}`}}
  else if(Scene.pendingActionPlan){const plan=Scene.pendingActionPlan,actor=Scene.actors.find(item=>item.id===plan.actorId),reappear=plan.phase==="reappear",destination=plan.phase==="destination",modifierDestination=destination&&plan.context?.destinationKind==="attack-modifier",assassination=reappear&&["skirmish","spell","finish"].some(key=>SceneEngine.actionIdIs(plan.actionId,key))&&Number(actor?.techniques?.["vagabond.assassin"]||0)>=2;phase=reappear||destination?"destination":"confirm";title=reappear?`${plan.actionName}: клетка появления`:modifierDestination?"Перелом позвоночника: телепортация":destination?`${plan.actionName}: клетка назначения`:`${plan.actionName}: подтвердить`;hint=reappear?(assassination?"«Ликвидация» разрешает выбрать любую свободную клетку, в том числе смежную с персонажем. Поле и ресурсы пока не изменятся.":"Выберите свободную клетку, не смежную с персонажами. Выбор сохранится в журнале, но поле и ресурсы пока не изменятся."):modifierDestination?"Выберите незанятую клетку, смежную с единственной Подброшенной целью. Телепортация, замена Атаки и оплата произойдут только после общего подтверждения.":destination?"Выберите итоговую клетку действия. Появление, оплата и действие будут применены одним пакетом.":`Все клетки составного действия ${actor?`для ${actor.name}`:""} сохранены. Подтвердите весь план; при отмене поле останется прежним.`;steps=sceneFlowSteps(modifierDestination?["Стычка","Вбить","Телепортация","Завершение Телом"]:["Действие","Появление",destination?"Назначение":"Подтверждение","Готово"],reappear?1:destination?2:2);actions=`${!reappear&&!destination?`<button type="button" class="primary" data-action-plan-continue>Подтвердить действие</button>`:""}<button type="button" data-scene-flow-cancel>Отменить без затрат</button>`}
  else if(pendingZealotPlan){const linePhase=pendingZealotPlan.phase==="lines",index=pendingZealotPlan.destinations.length,target=Scene.actors.find(actor=>actor.id===pendingZealotPlan.targetIds[index]);phase=linePhase?"area":"destination";title=linePhase?"Так не должно было быть: две Линии":`Сдвиг: ${target?.name||"персонаж"}`;hint=linePhase?`Выберите две пересекающиеся бесконечные Линии. Выбрано ${pendingZealotPlan.lines.length}/2 · R меняет направление. Озарение и ОД ещё не расходуются.`:`Выберите подсвеченную смежную клетку вне обеих Линий. Перемещено ${index}/${pendingZealotPlan.targetIds.length}; весь план подтвердится атомарно.`;steps=sceneFlowSteps(["Завершение","Две Линии","Сдвиги","Разрыв","Реакции"],linePhase?1:2);actions=`<button type="button" data-scene-flow-cancel>Отменить без затрат</button>`}
  else if(pendingCoreReaction){const actor=Scene.actors.find(item=>item.id===pendingCoreReaction.actorId),distance=Number(actor?.techniques?.["vagabond.untouchable"]||0)>=2?3:2;phase="destination";title=`Уворот: ${actor?.name||"цель"}`;hint=`Выберите свободную клетку в пределах ${distance} клеток. Допустимый итог сразу появится в журнале.`;steps=sceneFlowSteps(["Реакция","Клетка","Подтвердить"],1);actions=`<button type="button" data-scene-flow-cancel>Отменить</button>`}
  else if(pendingCoreAction){const action=D.actions.list.find(item=>item.id===pendingCoreAction),actor=currentHeroActor(),appearance=SceneEngine.actionIsAny(action,["skirmish","spell","finish"])&&sceneActorEffects(actor).includes("positive.исчез"),continuing=SceneEngine.actionIs(action,"step")&&(actor?.usedActions||[]).includes(action.id)&&Number(actor?.stepRemaining||0)>0,baseLimit=SceneEngine.actionIs(action,"jump")?Number(actor?.attrs?.talent||0):continuing?Number(actor?.stepRemaining||0):Number(actor?.speed||0),limit=sceneActorEffects(actor).includes("positive.ускорен")?baseLimit*2:sceneActorEffects(actor).includes("negative.замедлен")?Math.floor(baseLimit/2):baseLimit;phase="destination";title=appearance?`Ликвидация: клетка появления`:`${continuing?"Продолжить Шаг":action?.name||"Перемещение"}: клетка назначения`;hint=appearance?"Выберите любую пустую клетку: «Ликвидация» разрешает появиться и рядом с персонажем. После выбора начнётся Атака с преимуществом Ступени и критами на 5–6.":`Подсвечены свободные клетки в пределах ${limit}${SceneEngine.actionIs(action,"jump")?" по прямой Линии":""}. ${continuing?"ОД уже потрачено; используется сохранённое движение.":"Ресурс спишется после корректного выбора."}`;steps=sceneFlowSteps(["Действие","Клетка","Готово"],1);actions=`<button type="button" data-scene-flow-cancel>Отменить</button>`}
  else if(pendingEnemyStepActorId){const actor=Scene.actors.find(item=>item.id===pendingEnemyStepActorId),step=SceneEngine.actionByKey(D,"step"),available=actor&&SceneEngine.availableActions(Scene,D,actor.id).find(item=>item.id===step?.id),limit=Number(available?.continuation?available.remaining:actor?.speed||0);phase="destination";title=`Шаг: ${actor?.name||"противник"}`;hint=`Выберите подсвеченную свободную клетку в пределах ${limit}. ОД спишется только после корректного выбора; остаток движения можно использовать позже.`;steps=sceneFlowSteps(["Шаг","Клетка","Перемещение"],1);actions=`<button type="button" data-scene-flow-cancel>Отменить без затрат</button>`}
  else if(pendingEnemyRule){const actor=Scene.actors.find(item=>item.id===pendingEnemyRule.actorId),rule=enemyProfile(actor?.profileId)?.rules?.find(item=>item.id===pendingEnemyRule.ruleId),assassin=pendingEnemyRule.phase==="assassin-reappear";phase=assassin?"destination":"area";title=assassin?`${rule?.name||"Удар"}: появление`:`${rule?.name||"Действие врага"}: область`;hint=assassin?"Выберите свободную клетку рядом с выбранной целью. Ассасин появится в ней и сразу продолжит эту же Атаку с бонусом из Исчезновения.":"Наведите на поле, проверьте подсветку и выберите центр области.";steps=sceneFlowSteps(assassin?["Цель","Появление","Удар","Реакции"]:["Действие","Область","Цели","Реакции"],1);actions=`<button type="button" data-scene-flow-cancel>Отменить</button>`}
  else if(pendingTechniqueRule){const nails=pendingTechniqueRule.form==="nails",idol=pendingTechniqueRule.form==="idol";phase="area";title=`Техника: ${pendingTechniqueRule.name}`;hint=nails?`Выберите две пересекающиеся Линии длиной 3. Выбрано: ${pendingTechniqueLines.length}/2 · R меняет направление.`:idol?`Выберите 1–6 связанных клеток. Выбрано: ${pendingTechniqueCells.length}.`:`Выберите клетку${pendingTechniqueRule.shape==="line"?"; клавиша R поворачивает линию":""}. До подтверждения ресурсы не расходуются.`;steps=sceneFlowSteps(["Техника","Позиция","Эффект"],1);actions=`${idol?`<button type="button" class="primary" data-confirm-technique-cells ${pendingTechniqueCells.length?"":"disabled"}>Подтвердить клетки</button>`:""}<button type="button" data-scene-flow-cancel>Отменить</button>`}
  else if(battleOutcome){phase="result";title=battleOutcome==="victory"?"Противники выведены из боя":battleOutcome==="defeat"?"Герои выведены из боя":"Обе стороны выведены из боя";hint=gm?"Столкновение завершено. Зафиксируйте последствия в журнале или вручную верните участника в бой, если сцена продолжается.":battleOutcome==="victory"?"Столкновение завершено победой героев.":battleOutcome==="defeat"?"Столкновение завершено поражением героев.":"Столкновение завершено без действующей стороны.";steps=sceneFlowSteps(["Столкновение","Последний исход","Последствия"],2);actions=gm?`<button type="button" class="primary" data-scene-flow-director>Открыть итоги в пульте</button>`:""}
  else if(active){const progress=SceneEngine.turnActionProgressStatus(Scene,active.id),canControl=activeSceneView()==="gm"||active.heroId===S.id,current=progress.readyToEnd?progress.total+1:progress.currentAction;phase=progress.readyToEnd?"finish":"action";title=progress.readyToEnd?`Завершите Ход: ${active.name}`:`Действие ${progress.currentAction} из ${progress.total}: ${active.name}`;hint=progress.readyToEnd?`Все ${progress.total} действия использованы. Быстрые действия не занимают деление; завершите Ход, когда больше ничего не требуется.`:active.team==="enemy"?(compactLandscape?"Откройте «Цель» или «Враги».":`Осталось действий: ${progress.remaining}. Выберите действие противника в панели цели или отряда.`):active.heroId===S.id?`Осталось действий: ${progress.remaining}. Выберите базовое действие или Технику; Быстрое не сдвигает шкалу.`:"Ожидается действие текущего участника.";steps=sceneFlowSteps(progress.labels,current);actions=progress.readyToEnd?(canControl?`<button type="button" class="primary" data-scene-flow-end-turn>Завершить Ход</button>`:""):(active.heroId===S.id?`<button type="button" data-open-scene-panel="sheet">Открыть действия</button>`:"")}
  root.dataset.phase=phase;root.innerHTML=`<div class="scene-flow-copy"><span>${phase==="reaction"?"ОЖИДАЕТСЯ ОТВЕТ":phase==="resolve"?"ГОТОВО К УРОНУ":phase==="interrupted"?"ЦЕПОЧКА ПРЕРВАНА":phase==="finish"?"ХОД ГОТОВ К ЗАВЕРШЕНИЮ":phase==="result"?"СТОЛКНОВЕНИЕ ЗАВЕРШЕНО":"ТЕКУЩИЙ ЭТАП"}</span><strong>${esc(title)}</strong><small>${esc(hint)}</small></div>${steps}<div class="scene-flow-actions">${actions}</div>`;
}
